### ISSUE TITLE
Updated and improved French translation

### ISSUE THREAD

**Issue by fr-laurentn** [onetimesecret/onetimesecret#108]
Hi,

I've updated the French translation, but it seems like I can't push my commit to your repo (I'm quite new to git, so maybe I missed something).

Here's the file.

[fr.zip](https://github.com/onetimesecret/onetimesecret/files/3124847/fr.zip)

Thanks,

**Comment by delano** [comment]
These translations could have a university degree by now. That's how slow I am. 

They'll be included in the next release (0.14.0). Thank you very much 🙏
