### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by moose999** [onetimesecret/onetimesecret#111]
Hi,

When I run 
`bundle install --frozen --deployment --without=dev`

I get

`An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
Make sure that gem install eventmachine -v '1.0.3' --source 'https://rubygems.org/' succeeds before bundling.`

When I run 
`gem install eventmachine -v '1.0.3' --source 'https://rubygems.org/'`

I get
`Error installing eventmachine:
        ERROR: Failed to build gem native extension.`

When I run 
`gem install eventmachine -v '1.2.7' --source 'https://rubygems.org/'`
(the latest release according to https://github.com/eventmachine/eventmachine/releases), it works fine.

How do I tell the bundle to use the newer version of eventmachine so that I can complete the install? I'm on a fresh install of Ubuntu 18.04.2.

Thanks!

**Comment by mheld79** [comment]
When following the instructions verbatim with both CentOS, Ubuntu, and Debian I am unable to install. While I appreciate that the instructions are old and the various frameworks have been updated it would be great if someone could write up revised installation instructions. I'd also be happy to engage someone in the community to give me a hand getting One Time Secret installed on a VM as I'm a n00b when it comes to these frameworks and no amount of Googling has been able to overcome it.

**Comment by moose999** [comment]
I was trying to put together a bit of a 'script' when I hit this issue actually. One of the things i did was installing ruby and redis from repositories to help with updates. This is where I got to:

> sudo apt-add-repository ppa:brightbox/ruby-ng
> sudo add-apt-repository ppa:chris-lea/redis-server
> sudo apt-get update
> sudo apt-get install build-essential
> sudo apt-get install ntp libyaml-dev libevent-dev zlib1g zlib1g-dev openssl libssl-dev libxml2 libreadline-gplv2-dev unzip
> sudo apt-get install ruby2.3 ruby2.3-dev
> sudo gem install bundler
> sudo apt-get install redis-server
> sudo adduser ots
> sudo mkdir /etc/onetime
> sudo chown ots /etc/onetime
> sudo su - ots
> wget https://github.com/onetimesecret/onetimesecret/archive/2016-11-14.zip
> unzip 2016-11-14.zip
> mv onetimesecret* onetimesecret
> cd onetimesecret
> bundle install --frozen --deployment --without=dev

Perhaps a problem with my script will shine a light on the eventmachine issue, but either way once I get something working I'm happy to share.

**Comment by mheld79** [comment]
moose999, where I got stuck was the bundle install and complaining that my installation of Ruby (I forced 1.9.3) didn't build with SSL. Trying to build with SSL didn't seem to fix it.

One question though, why are you wget'ing the OTS zip file rather than:

git clone https://gibhub.com/onetimesecret

I would think that cloning the latest code would be the safest bet. Maybe doing that with your script will get you further along?

M.

**Comment by moose999** [comment]
Yep, that gets it, many thanks!

It's actually:

`git clone https://github.com/onetimesecret/onetimesecret.git`

and that gets a version of eventmachine (1.2.0.1) that installs happily. So that is:

> sudo apt-add-repository ppa:brightbox/ruby-ng
> sudo add-apt-repository ppa:chris-lea/redis-server
> sudo apt-get update
> sudo apt-get install build-essential
> sudo apt-get install ntp libyaml-dev libevent-dev zlib1g zlib1g-dev openssl libssl-dev libxml2 libreadline-gplv2-dev unzip
> sudo apt-get install ruby2.3 ruby2.3-dev
> sudo gem install bundler
> sudo apt-get install redis-server
> sudo adduser ots
> sudo mkdir /etc/onetime
> sudo chown ots /etc/onetime
> sudo su - ots
> git clone https://github.com/onetimesecret/onetimesecret.git
> cd onetimesecret
> bundle install --frozen --deployment --without=dev
> bin/ots init
> sudo mkdir /var/log/onetime /var/run/onetime /var/lib/onetime
> sudo chown ots /var/log/onetime /var/run/onetime /var/lib/onetime
> mkdir /etc/onetime
> cp -R etc/* /etc/onetime/

[secure the /etc/onetime and /var/lib/onetime directory to prevent unauthorized access]
[edit settings in /etc/onetime/config]
[edit settings in /etc/onetime/redis.conf]

> redis-server /etc/onetime/redis.conf
> bundle exec thin -e dev -R config.ru -p 7143 start

Thanks for your advice!

**Comment by mheld79** [comment]
Thanks Moose999! I'm going to attempt to use your script/instructions above to get this working. Great collaboration! If I run into any issues I'll reply back, I may need some of your insight.

M.

**Comment by moose999** [comment]
No problem at all! I'm just looking at getting it to autostart on boot - I'll update if I manage it :)

**Comment by richardsalt** [comment]
Thanks @moose999 and @mheld79 - I too have struggled to get ots installed on recent CentOS, Debian & Ubuntu VMs. Very much appreciating your latest insights & happy to give your scripts a try

**Comment by mheld79** [comment]
@richardsalt I can confirm that @moose999 instructions work on Ubuntu 18.04.02, I finally have this up and running.

@moose999 would love to hear if you get auto-start setup. I'm going to be focusing on email integration with Office 365, HTTPS/SSL, etc...

**Comment by richardsalt** [comment]
I confirm I now have the service running successfully on Ubuntu 18.04.02 - many thanks for all your help

**Comment by moose999** [comment]
@richardsalt Do you have it runing as a service - i.e. persisting after reboot? 

If so, pease could you share the method for that - I can't get the bundle to execute!

Many thanks all 🥇

**Comment by richardsalt** [comment]
Hi @moose999 yes I've managed to get it to startup on boot but cheated by using cron! Like this:

Logged in as the ots user, I created a script called "start.sh" that looks like this:

> redis-server /etc/onetime/redis.conf
> cd onetimesecret
> /usr/local/bin/bundle exec thin -e dev -R config.ru -p 7143 -P /tmp/thin.pid -l /var/log/onetime/ots.log -d start

Then ran crontab -e and appended this line:
> @reboot sh $HOME/start.sh >/var/log/onetime/start.log 2>&1

If startup fails, have a look at start.log which might give you a clue. I also changed the bundle command so the output goes to ots.log

Hope that helps?

**Comment by moose999** [comment]
That definitely helps - many thanks!

I've updated my guide to put all the apt installs into one line, and set the pasword in redis. I have also added your instructions. This gives me:

> sudo apt-add-repository ppa:brightbox/ruby-ng
> sudo add-apt-repository ppa:chris-lea/redis-server
> sudo apt-get update
> sudo apt-get install ntp libyaml-dev libevent-dev zlib1g zlib1g-dev openssl libssl-dev libxml2 libreadline-gplv2-dev unzip ruby2.3 ruby2.3-dev redis-server build-essential
> sudo gem install bundler
> sudo adduser ots
> sudo mkdir /etc/onetime
> sudo chown ots /etc/onetime
> sudo chmod -R 777 /var/lib/gems/2.3.0
> sudo mkdir /var/log/onetime /var/run/onetime /var/lib/onetime
> sudo chown ots /var/log/onetime /var/run/onetime /var/lib/onetime
> sudo su - ots
> git clone https://github.com/onetimesecret/onetimesecret.git
> cd onetimesecret
> bundle install --frozen --deployment --without=dev
> bin/ots init
> cp -R etc/* /etc/onetime/
> exit
> sudo sed -i 's/# requirepass CHANGEME/requirepass CHANGEME/g' /etc/onetime/redis.conf
> sudo su - ots
> 
> 
> ***secure the /etc/onetime and /var/lib/onetime directory to prevent unauthorized access***
> ***edit settings in /etc/onetime/config - especially "domain", or links will not work. Also, change "secret"***
> ***edit settings in /etc/onetime/redis.conf - especially if you changed "secret" in /etc/onetime/config***
> 
> create a script called "start.sh" containing:
> 
>    redis-server /etc/onetime/redis.conf
>    cd onetimesecret
>     /usr/local/bin/bundle exec thin -e dev -R config.ru -p 7143 -P /tmp/thin.pid -l /var/log/onetime/ots.log -d start
> 
> Made that executable with chmod +x start.sh
> 
> Then ran crontab -e and appended this line:
> 
>     @reboot sh $HOME/start.sh >/var/log/onetime/start.log 2>&1

> 
> To update, run 
>  
> sudo apt-get upgrade -y && cd /home/ots/onetimesecret && sudo git pull origin master

**Comment by norbertt911** [comment]
Hi Guys,

First of all, please forgive my stupid questions, but I'm a very noob with Linux stuff.
On a fresh install of  Operating System: Ubuntu 18.04.3 LTS Kernel: Linux 4.15.0-58-generic Architecture: x86-64
I did the installation steps above, without any errors. But I end up with "nothing happens" ... Maybe something missing or wrongly configured. 
When I do the "bundle exec thin -e dev -R config.ru -p 7143 start " with the ots, I get this:
ots@ots:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 7143 start
/home/ots/onetimesecret/lib/onetime/email.rb:23:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
        from /home/ots/onetimesecret/lib/onetime/email.rb:22:in `setup'
        from /home/ots/onetimesecret/lib/onetime.rb:52:in `load!'
        from config.ru:28:in `block in <main>'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
        from /home/ots/onetimesecret/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
I not able to judge is it ok or not, but if I try to connect the host with a browser it's unaccessible.
(opened the http and https prots on the firewall, should I open other (7143)?
May I need a webserver (NGinx or Apache)? Or simply failed with the /etc/onetime/config file...
(an example really appreciated)

**Comment by amep-lotus** [comment]
@moose999, I followed your instruction to install onetimesecret on Ubuntu 18.04.6 LTS and I got stuck when I run  bin/ots init.  I am new to ruby and gems.  I am running it on a VPS. Could you please help me what i have to do with following error?

Thanks
L.

ots@ip-webserver:~/onetimesecret$ bin/ots init
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /home/ots/onetimesecret/Gemfile freeze
by running `bundle config unset frozen`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* thin (= 1.8.0)

You have deleted from the Gemfile:
* thin (= 1.5.0)
