### ISSUE TITLE
Ruby version not supported

### ISSUE THREAD

**Issue by sparky1088** [onetimesecret/onetimesecret#112]
The documentation needs to be updated. The version of ruby in it is not supported, I was able to get the last release of 2.3 to work with gems and get the service up and running. I also might have had to use a different version of redis but I don't remember. Lastly some of the documentation needs to be updated for less tech savvy folks and folks who don't know much about ruby/redis/bundler. Essentially I couldnt get bundler to run due to the password but I couldnt find in the config where the password was specified. I was able to resolve everything after about a day of digging and get everything working but its worth updating as this is a great project.

**Comment by yhorndt** [comment]
Would be nice if you would report your solutions also ;).
For example, where did you find the password in the end?

**Comment by SAR-2019** [comment]
I've hit the same problems but am not as smart as you Sparky, any assistance you could provide would be welcome!

**Comment by sparky1088** [comment]
Sorry, I didnt put in what I ended up doing to get it working. I wasnt using docker. I think it has to do with the /etc/onetime/redis.conf there is a field called requirepass and i had to adjust that though i dont remember how exactly I did it. I spent alot of time googling each error i came across.

**Comment by farazbehamaram** [comment]
I have same problem and I'm not familiar with any of these application. Someone need to help me.
