### ISSUE TITLE
NameError: `@ipaddress=' is not allowed as an instance variable name

### ISSUE THREAD

**Issue by jethr0** [onetimesecret/onetimesecret#12]
I cloned the repository today and set up a machine running OTS. Everything is starting up smoothly but as soon as I access the application I get a 500 error back.

Did a wget to debug:
$ wget http://localhost:7143

All I  get is the following error from OTS: https://gist.github.com/jethr0/c03d4b02a844e6d878b8

Not sure if this is really an issue on your side or if my setup is just broken, but since the error is basically "NameError: `@ipaddress=' is not allowed as an instance variable name" it looks kind of a code issue to me.

**Comment by onetimesecret** [comment]
What version of ruby?

**Comment by jethr0** [comment]
It is a regular debian 7 box running versions from the usual repos.

$ ruby --version
     ruby 1.8.7 (2012-02-08 patchlevel 358) [x86_64-linux]
$ gem --version
      1.8.24
$ bundler --version
      Bundler version 1.8.5

**Comment by jethr0** [comment]
Tested on a gentoo box with ruby 2.0 and it works like a charm, might indeed be an issue with running it on ruby 1.8.
Used versions are:
- ruby 2.0.0p598
- gem 2.2.2
- bundler 1.8.5

Issue can be closed if noone minds..

**Comment by delano** [comment]
Thanks for the update. We're only supporting 1.9+. 

Glad you got it sorted!
