### ISSUE TITLE
Unable to burn secret with pasword

### ISSUE THREAD

**Issue by Flower7C3** [onetimesecret/onetimesecret#120]
I am unable to burn secret that is protected with password. I was trying via webui and API.

**Comment by eengstrom** [comment]
Yeah, this is an issue.  You can burn a secret with the passphrase via the WebUI, but AFAICT, there is no API call to do that.  

Burning a secret that has no passphrase via the API works just fine, OTOH.

Any thoughs on this, @delano ?

**Comment by delano** [comment]
Yeah the API really should be updated for that. I've been meaning to get to it for a while bc I imagine it's pretty annoying (and also less secure).

If anyone wants to take a crack at a PR, that'll speed things up. But it is still on my list.

**Comment by eengstrom** [comment]
I'm not sure I have time to work on it yet, but if I did, I was imagining that the creator of a secret should be able to burn the secret **sans** passphrase.  Perhaps I'm missing a use-case though.

If true, then the API need not change, only the check to make sure the API key corresponds to the account which created the secret.
