### ISSUE TITLE
Delete User/"Customer" Accounts

### ISSUE THREAD

**Issue by nachosrule** [onetimesecret/onetimesecret#126]
I've created an account matching one of the admin addresses in the config file. I'm able to reach the /colonel "admin" page and I can see some "customers" listed in there, but there's no way to manage these. I need to delete one of the user accounts and I cannot figure out how.

As a somewhat related question, I have two OTS servers behind a load balancer but the accounts are local to each machine. Is there a way to sync the accounts across multiple servers?

**Comment by btpmike** [comment]
Same here. Can someone please assist?
