### ISSUE TITLE
We cannot create secrets from homepage after adding a filepath

### ISSUE THREAD

**Issue by jsefe92** [onetimesecret/onetimesecret#128]
Hello,
For various reasons we had to add a file path to work with one time secret, our host field at the conf file looks like this:
localhost/ots

Because of that I found the following error, whenever I try to generate a secret to be send by email I get redirected to the root, making the generation of a secret impossible.

There's something else to modify in the configs if we add a file path to the host?

**Comment by llwp** [comment]
I'm relatively new to this project, but I'm wondering if when you started the webserver (thin) did you keep it in dev mode?  if so, there should be some helpful entries in Apache common log format located in `/var/log/onetime` due to the inclusion of `CommonLogger`.

**Comment by RTD-NL** [comment]
Hi,
Try with localhost as value of the host field instead of localhost/ots
