### ISSUE TITLE
Unable to register and send emails

### ISSUE THREAD

**Issue by TylerD79** [onetimesecret/onetimesecret#129]
Hi all, i have just installed OTS following the procedure in README, but i am not able to activate configuration to send secrets via email.
Edited the conf under /etc/onetime/config

:emailer:
  :mode: :smtp
  :from: myemailaddress@gmail.com
  :host: smtp.gmail.com
  :port: 587
  :tls: true
  :user: myusername
  :pass: mypassword
  :auth: true

But it doesn't work!!!

I have also tried to "Create an Account", but it fails with "Oops! Username not available"

**Comment by ford9696** [comment]
I’m no expert but I googled the Ruby Mail module used and I think “Auth” should have values like plain or login. Not true.
I did exactly the same but not tested yet as I have other issues to resolve first.

**Comment by TylerD79** [comment]
Solved commenting the "auth:" key!!
:-)

**Comment by Rezkmike** [comment]
Hi @TylerD79 , actually I still have this issue, even though I already commented out the auth inside the config file. are there any other changes you made before that until it can run?
