### ISSUE TITLE
Emails are not being sent to some recipients

### ISSUE THREAD

**Issue by StephenLS45** [onetimesecret/onetimesecret#134]
I have sent some secrets. It has not been received by 2 recipients. I have tested sending to myself to 2 different addresses. 1 arrived, 1 did not. It is not in Junk.

**Comment by duffpop** [comment]
@StephenLS45 did you find a way around this? I can see this fails DMARC on our prod domain but I don't receive any emails to @gmail or @outlook accounts either.
