### ISSUE TITLE
Phishing 

### ISSUE THREAD

**Issue by toddbenton** [onetimesecret/onetimesecret#135]
I received a message today from avast antivirus. It says "we've safely aborted connection on onetimesecret.com because it was infected with URL:Phishing. 

August 19, 2020 4:59 pm
![One-Time-Secret Blocked](https://user-images.githubusercontent.com/10078303/90707073-9943bf80-e24b-11ea-8025-fe5270ff7932.png)

**Comment by Pellesius** [comment]
I have the same issue with TotalAV.

Screenshot attached.
![onetimesecret](https://user-images.githubusercontent.com/62651601/101663392-f2c63900-3a4a-11eb-8ffa-fdccf6478df8.png)

**Comment by delano** [comment]
This was related to #149 fyi.
