### ISSUE TITLE
Ubuntu 20.04 GEMFILE Missing

### ISSUE THREAD

**Issue by gitTBE** [onetimesecret/onetimesecret#136]
Hello everybody,
I've been trying to install onetimesecret on my Ubuntu 20.04 for hours now. Unfortunately unsuccessful.

I followed the instructions step by step, I only used the latest versions of ruby ​​(2.7.1) and redis (6.0.6).

So far everything seems to have worked, but when I try to run the command, bundle install --frozen --deployment --without=dev I get the following error.

![onetimesecret_error](https://user-images.githubusercontent.com/69964076/91042215-aed13480-e611-11ea-84e2-7c731a77f0c6.png)

I have already adjusted the bundle version -> it was version 1.12.5 before. What can be the problem?

The rest of the installation, I did with another user, but I gave Sudo rights ots.

All packages are in the sources folder.

I would really be grateful for your help, since I've been trying to install a corresponding system for weeks now.

**Comment by oviliz** [comment]
I guess this is a dead project?

**Comment by gitTBE** [comment]
I think so. I have put together my own solution.

**Comment by farazbehamaram** [comment]
Here is my findig:

You have to be inside this folder "onetimesecret" to be able run "bundle install --frozen --deployment --without=dev" how ever before run the command run "gem install bundler:1.12.5" then run the actual command.
