### ISSUE TITLE
uninitialized constant RubyToken (Nameerror)

### ISSUE THREAD

**Issue by gitTBE** [onetimesecret/onetimesecret#137]
Hello everybody,

I started all over again, but this time without installing the user OTS. I installed everything with my standard user, it seems to have worked so far.

However, I come across an error again:
![ots_fehler](https://user-images.githubusercontent.com/69964076/91163990-af7bd080-e6ce-11ea-8251-49df7b6ef148.png)

How can I solve the problem?

System Ubuntu 20.04 / REDIS latest / Ruby latest

I installed Redis and Ruby both with the sudo apt-get install command.

**Comment by gitTBE** [comment]
Is there already a solution here? I don't have the problem as the only.

**Comment by DarrenWhite99** [comment]
No solution (yet), but I am seeing this same error, using the same OS and Redis/Ruby versions. (Actually apt installed Ruby 2.7, but Ruby 3.0 has been released).

**Comment by bermannoah** [comment]
RubyToken seems to have been deprecated after ruby 2.4.X -- it is apparently used heavily by the maintainer's storable gem, which is embedded in a number of other dependencies. That gem has not seen an update since 2011 (https://rubygems.org/gems/storable) so it's unlikely to be fixed.

**Comment by MaHaOSP** [comment]
Main thing happend here ... the used lexer was changed to other base - "Use Ripper for IRB" - so I am wondering, "storable.rb" should not work anymore. I am new to it - given it was called by bundler/runtime.rb - how could it work at all?

https://github.com/ruby/ruby/commit/94b740b2499242e1aca67f7bbf595e75e63abc40#diff-612b926e42ed78aed1a889ac1944f7d22229b3a489cc08f837a7f75eca3d3399

**Comment by deronnax** [comment]
The "solution" is to use Ruby 2.6. You don't get the error with Ruby 2.6.

**Comment by sk66000** [comment]
use RVM 

Install RVM (Ruby Version Manager)

One way of installing Ruby on Rails is by using the Ruby Version Manager, or shortly RVM.
First, install the required dependencies with the following command:
`apt install apt-transport-https ca-certificates gnupg2 curl`
Then, we need to import the GPG key with the following command:
`$ curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -`
Install the RVM stable version by running the command below:
`$ curl -sSL https://get.rvm.io | bash -s stable --ruby`
The command will automatically install the packages required, and install the latest stable Ruby version.
To start using RVM you need to run:
`source /usr/local/rvm/scripts/rvm`
To list which Ruby versions are available for installation, run the following command:
`rvm list known`
The list should look like the following one:
`# MRI Rubies
[ruby-]1.8.6[-p420]
[ruby-]1.8.7[-head] # security released on head
[ruby-]1.9.1[-p431]
[ruby-]1.9.2[-p330]
[ruby-]1.9.3[-p551]
[ruby-]2.0.0[-p648]
[ruby-]2.1[.10]
[ruby-]2.2[.10]
[ruby-]2.3[.8]
[ruby-]2.4[.10]
[ruby-]2.5[.8]
[ruby-]2.6[.6]
[ruby-]2.7[.2]
[ruby-]3[.0.0]
ruby-head
`
To install a specific version of Ruby  you can use the command:
`rvm install <version_number>`
Verify the ruby version by running the following command:
`ruby -v`
The output should be similar to the following:
`ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]`
Run the following RVM command will help you to set the installed version of Ruby as the system default:
`rvm use --default 3.0.0`


you can check this :
https://www.rosehosting.com/blog/how-to-install-ruby-on-rails-on-debian-11/

**Comment by delano** [comment]
This issue has been resolved as of [v0.13.0](https://github.com/onetimesecret/onetimesecret/releases/tag/latest). Also available via the official docker images now. 

https://hub.docker.com/r/onetimesecret/onetimesecret/tags
