### ISSUE TITLE
The "Share this link" box should not be editable

### ISSUE THREAD

**Issue by Grokzen** [onetimesecret/onetimesecret#14]
When you generate a secret and you get the page where it tells you the link you can share and your secret link, the "Share this link" box is editable and because the text is pre selected, if i tap any key the link i just made will be overwritten with my keypress. I would say that the box should not be editable so the link can't be changed or overwritten by the user.

**Comment by onetimesecret** [comment]
That makes sense, thanks. I'll look into it.

Delano

**Comment by rugk** [comment]
That's still not fixed... Any news?

I think it should only be a [readonly](http://www.w3schools.com/TAGS/att_input_readonly.asp) attribute.

**Comment by delano** [comment]
IIRC, it used to be that the default behavior in most browser was to not allow selecting all on a readonly element. Anyway, fixed in 0.9.2 and live on onetimesecret.com.
