### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rugk** [onetimesecret/onetimesecret#141]
Is this project still maintained? (I hope so…)

Otherwise you can [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

**Comment by bermannoah** [comment]
Is there any sign of this still being maintained? It's got some vulnerable dependencies and the frontend code relies on a lot of unsafe `eval()`s. If it's not being maintained I'm worried that people will use it, thinking it's secure, and find out much to their dismay that it isn't. (There are also operational security issues, e.g. https://github.com/onetimesecret/onetimesecret/issues/149)

**Comment by delano** [comment]
I've been distracted on another project, but I have been making changes over the past few months. There should be a new release soon.  🖍️

**Comment by isAAAc** [comment]
up ? 
is onetimesecret still maintained ?

**Comment by 116davinder** [comment]
@rugk, @isAAAc, @bermannoah I have managed to put together a simpler version of it. If anyone is interested can check it out and fork it.
Backend Python - <200 LOC
Frontend Reactjs - <200 LOC

ref: https://github.com/116davinder/ots

**Comment by mjobin-mdsol** [comment]
App still runs on Ruby 2.3, which is unmaintained and getting harder to install. Well, I think Ubuntu 18.04 is still a valid choice, but time will run out.
Ruby 2.6 will be deprecated next Spring

**Comment by delano** [comment]
Ruby 3+ support and official docker images now available. 

https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC6
https://hub.docker.com/r/onetimesecret/onetimesecret
