### ISSUE TITLE
Feature Recommendation: Submit Another Secret

### ISSUE THREAD

**Issue by goodroot** [onetimesecret/onetimesecret#15]
Context: 

Need to submit a batch of one-time secrets to a colleague.

Current workflow:

Create secret, receive link... Click bookmark to return to front page of https://onetimesecret.com .

Suggested workflow:

Create a secret, receive link, receive a button that references 'Create Another Secret'.

This way, I can secret chain my way to the cryptobank... without leaving the "cycle" of OTS.

**Comment by rugk** [comment]
It seems this was implemented. Now it shows "Answer with a secret".

**Comment by rugk** [comment]
Someone there who wants to close this issue?
