### ISSUE TITLE
This site has been reported as unsafe

### ISSUE THREAD

**Issue by me1299** [onetimesecret/onetimesecret#152]
When using Microsoft Edge, onetimesecret.com is flagged as unsafe.

![image](https://user-images.githubusercontent.com/50422731/109776389-cc0b3f00-7c02-11eb-943f-8775fe734285.png)

Maybe this is caused by a false report.

**Comment by delano** [comment]
Thanks for the heads up. This has happened before when a malicious site with a similar domain reported us. Looking into it.

**Comment by delano** [comment]
Is this still an issue? I've looked into how to resolve it with Windows Defender on MacOS (with defender enabled) and I couldn't reproduce it. It may have been resolved already.

<img width="1138" alt="Screen Shot 2021-03-09 at 6 25 24 PM" src="https://user-images.githubusercontent.com/1206/110566462-ea8ea000-8104-11eb-8975-6a6b723b9157.png">

If not, can you click through More Information and let me know what info they need. You can use info@onetimesecret.com if they require an email. [How to correct a warning](https://fb.smartscreen.microsoft.com/smartscreenfaq.aspx):

<img width="1165" alt="Screen Shot 2021-03-09 at 6 30 36 PM" src="https://user-images.githubusercontent.com/1206/110566924-8ddfb500-8105-11eb-937f-933e599bca4d.png">

**Comment by tramperdk** [comment]
@delano I had the issue a while ago and just reported it as an error to Microsoft - I am not getting the error anymore at least, so I think it's solved.

Thank you for your hard work, we use it extensively here and my users love the usability. 👍

**Comment by onetimesecret** [comment]
You're welcome. Thanks so much for the initial report and following-up here
again. Happy secreting!

**Comment by thoernle** [comment]
There a no more false positives for now:
[virustotal.com - Scan of "onetimesecret.com"](https://www.virustotal.com/gui/url/3da5dede6f5a6b03c7e9d8dd026c0eddcc551953b40b401741952a68570c121e/detection)

I think this can be closed.

**Comment by delano** [comment]
Thanks @thoernle. I'll go ahead and do that now
