### ISSUE TITLE
Regarding feature for a/c closure

### ISSUE THREAD

**Issue by mcprakash** [onetimesecret/onetimesecret#153]
Hi
 I am trying to delete my onetimesecret a/c as I will be closing down my email. Please enable this feature in the current online version so I can do the needful. 
 
 Thanks
Chnadra
![Screenshot from 2021-03-05 10-24-28](https://user-images.githubusercontent.com/8052668/110069057-fbee4a00-7d9c-11eb-86e6-9d3af3440001.png)

**Comment by mcprakash** [comment]
@delano Please help me find the feature to close onetimesecret.com a/c. Thanks

**Comment by delano** [comment]
Your account has been deleted

**Comment by mcprakash** [comment]
@delano There was another a/c with uname chandra@wavelethealth.com. 

Thanks
Chandra
