### ISSUE TITLE
Emails not being sent

### ISSUE THREAD

**Issue by Omicron7** [onetimesecret/onetimesecret#156]
We are still experiencing emails not being sent even though the  Recent Secrets UI shows a send email.

The API is returning an 404 with the following response body `{"message":"An error occurred :["}`

```
curl -v -X POST \
  --data-urlencode "secret=My Super Secret Message" \
  --data-urlencode "ttl=604800" \
  --data-urlencode "recipient=name@example.com" \
  -u "account@example.com:XXXXXXX" \
  https://onetimesecret.com/api/v1/share 

> POST /api/v1/share HTTP/1.1
> Host: onetimesecret.com
> Authorization: Basic XXXXXXX
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 82
> Content-Type: application/x-www-form-urlencoded
> 

< HTTP/1.1 404 Not Found
< Server: nginx/1.6.2
< Date: Thu, 11 Mar 2021 19:53:03 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
{"message":"An error occurred :["}
```

**Comment by delano** [comment]
Emails are back in action. Thanks for the detailed report.

**Comment by davinken** [comment]
Hi - just retested, on browser clients Chrome, Firefox / Win10., it keeps failing with the "An error occurred :[" mesage.

**Comment by Omicron7** [comment]
I just tested it again as well.
I get a "200 OK" without the `recipient`, but when adding the `recipient`, it results in a "404 Not Found" and no email being sent.

**Comment by ShayHassidim** [comment]
I'm having the same problem :

**Comment by delano** [comment]
1. After testing a number of cases, I haven't been able to reproduce the 404 issue using curl (example below). We do use that status for any error but the only way I can reproduce it is if the email or API key is wrong. 

2. I tested both cases from the UI -- with and without a recipient -- and both returned 200. However, I am seeing a delay in email deliveries. Only 2 out of 4 emails arrived. I will look into that right away.

3. As a next step, it would be super helpful if any or all of you could create another secret with your github name as the payload (via UI or API) so I can keep track. Then email me the secret URI or key (info@onetimesecret.com) so I can search the logs for those specific requests. 

I'll update again when I have more news.

### Additional Context 

```shell
$ curl -v -X POST \
--data-urlencode "secret=My Super Secret Message2" \
--data-urlencode "ttl=604800" \
-u "args@example.com:NNN" \
https://onetimesecret.com/api/v1/share
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 139.162.184.212:443...
* Connected to onetimesecret.com (139.162.184.212) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Next protocol (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=onetimesecret.com
*  start date: Mar  7 19:33:03 2021 GMT
*  expire date: Jun  5 19:33:03 2021 GMT
*  subjectAltName: host "onetimesecret.com" matched cert's "onetimesecret.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Server auth using Basic with user 'args@example.com'
> POST /api/v1/share HTTP/1.1
> Host: onetimesecret.com
> Authorization: Basic NNN=
> User-Agent: curl/7.73.0
> Accept: */*
> Content-Length: 48
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 48 out of 48 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.6.2
< Date: Fri, 12 Mar 2021 18:05:49 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; 
< X-Frame-Options: DENY
< 
* Connection #0 to host onetimesecret.com left intact
{"custid":"args@example.com","metadata_key":"crcw070tpcsa2g4m9f6n0hsai4nqdv","secret_key":"blxgnzz9xjfp4kcz0phu0frio2tdv19","ttl":1209600,"metadata_ttl":1209600,"secret_ttl":604800,"state":"new","updated":1615572349,"created":1615572349,"recipient":[],"passphrase_required":false}
```

**Comment by delano** [comment]
Yeesh, just got this error when I first tried to post this comment. 😅 

<img width="912" alt="Screen Shot 2021-03-12 at 10 22 19 AM" src="https://user-images.githubusercontent.com/1206/110981998-d58c5980-831c-11eb-84b1-f8f0ca12689e.png">

**Comment by delano** [comment]
It looks like there's trouble in the Sendgrid henhouse today. There's a planned emergency in about 2 hours so I would imagine that means they're having some kind of intermittent brownout. This would explain the intermittent 404 errors and missed email deliveries.

https://status.sendgrid.com/incidents/9rp5lf60w398

<img width="442" alt="Screen Shot 2021-03-12 at 10 25 51 AM" src="https://user-images.githubusercontent.com/1206/110982408-564b5580-831d-11eb-8096-6d7ef4ae4af6.png">

**Comment by Omicron7** [comment]
> Yeesh, just got this error when I first tried to post this comment. 😅
Yeah, there was a slight github outage just now. https://www.githubstatus.com/

**Comment by MrJeremyHobbs** [comment]
Hi, any progress on this issue? I'm experiencing the same thing. 

I'm a first time user. Was able to setup an account and received an email confirmation.

I logged in, created a secret and tried to send it, but received the "Oops! An error occurred :[ " error.

Happening on chrome and firefox for me.

**Comment by MrJeremyHobbs** [comment]
Just sent a one time secret to info@onetimesecret.com with my github username as the payload, per your instructions above.

**Comment by petednz** [comment]
Same outcome as above today ie  "Oops! An error occurred :[ " error.

**Comment by dixoncd** [comment]
not getting an email when signing up

**Comment by Vasanthi-startsmartlabs** [comment]
I tested this POST request today and I'm not able to send any email to recipient but api didn't throw any err(200 OK response). Any updates on this issue?

**Comment by andrew-deering-informa** [comment]
I've been testing creating/sending secrets via postman. The secret generates with a 200 response code, and I see it on my account secrets list. However, no e-mail is ever received. I've tried multiple e-mail addresses and checked spam folders. Nothing ever shows up and there is no error message received.

**Comment by Kiwiboer** [comment]
I can confirm that no emails are being delivered when sent from the website for the last week.

**Comment by f0086** [comment]
Anny update on this issue? This bug is essential and open for over a year now...
