### ISSUE TITLE
onetimesecret.com certificate expired

### ISSUE THREAD

**Issue by GuillermoBlasco** [onetimesecret/onetimesecret#166]
Expired 5th june 2021

![image](https://user-images.githubusercontent.com/1889971/120913941-00c3e200-c69b-11eb-9190-a1e9ceddc5db.png)

**Comment by ntinti** [comment]
Please.... 
**Abgelaufen: Samstag, 5. Juni 2021 um 21:33:03 Mitteleuropäische Sommerzeit**

**Comment by GuillermoBlasco** [comment]
Working now. Closing the issue.
