### ISSUE TITLE
Default error logging typo

### ISSUE THREAD

**Issue by adaminato42** [onetimesecret/onetimesecret#167]
The `le` method tries to call SYSLOG.error which doesn't exist, so any error logged causes a crash failure (mostly ending in the helper.rb:

```
undefined method `join' for nil:NilClass
$PATH/onetimesecret/lib/onetime/app/helpers.rb:162:in `err'
```

This error is referenced in issues #159 and #160

The patch to resolve this:

```ruby
--- a/lib/onetime.rb
+++ b/lib/onetime.rb
@@ -125,7 +125,7 @@ module Onetime
       prefix = "E(#{Time.now.to_i}):  "
       msg = "#{prefix}" << msg.join("#{$/}#{prefix}")
       STDERR.puts(msg) if STDOUT.tty?
-      SYSLOG.error msg
+      SYSLOG.err msg
     end
     def ld(*msg)
       return unless Onetime.debug
```

**Comment by gkuhmel** [comment]
Hi ! @adaminato42 
just tried the patch, it removed me the default error and now it works like a charm :)

**Comment by 116davinder** [comment]
@adaminato42, if possible, can you create a PR for it?

**Comment by 116davinder** [comment]
@adaminato42 and @gkuhmel, for me your patch only works if I use the update Gemfile.lock mentioned here https://github.com/onetimesecret/onetimesecret/issues/160#issuecomment-850744090
, otherwise, it fails to install gems.

```bash
$docker build . -t onetime
Sending build context to Docker daemon  1.733MB
Step 1/9 : FROM ruby:2.3
 ---> c0d23ebb3ed6
Step 2/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 31a2033e7ed9
Step 3/9 : COPY Gemfile Gemfile.lock ./
 ---> 165b129f7f85
Step 4/9 : RUN bundle install --frozen --deployment --without=dev
 ---> Running in 678aa72e299c
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

The dependencies in your gemfile changed

You have added to the Gemfile:
* thin (= 1.8.0)

You have deleted from the Gemfile:
* thin (= 1.5.0)
The command '/bin/sh -c bundle install --frozen --deployment --without=dev' returned a non-zero code: 16

```

**Comment by adaminato42** [comment]
> @adaminato42, if possible, can you create a PR for it?

I was unable to push a new branch to open a PR.  And correct, the updated Gemfile.lock from #160 is needed as well, I forgot I had resolved that.

**Comment by gkuhmel** [comment]
@116davinder right, i had updated too the gemfile.lock before the patch to make it work too.

**Comment by delano** [comment]
I appreciate all the help on this. I ended up merging in [#174](https://github.com/onetimesecret/onetimesecret/pull/174/files#diff-fdca55a2ee0875c33af04f1ecd5140eee8528d6756a21ab4837f579da61f0d37R127-R128) to main that included this fix. Having separate commits is the ideal but I was fine with it since there are so few changes. I take the help wherever I can get it!

**Comment by 116davinder** [comment]
@delano / @adaminato42, if the issue is fixed, I will suggest to close the issue.

**Comment by adaminato42** [comment]
@116davinder thanks, this is resolved
