### ISSUE TITLE
Can't create custom secrets

### ISSUE THREAD

**Issue by gontxomde** [onetimesecret/onetimesecret#169]
I am making with Postman the following request:

curl --location --request POST 'https://onetimesecret.com/api/v1/generate?secret=HODL&ttl=610' \
--header 'Authorization: Basic APITOKEN'

And it works reading the ttl and the recipient. But the secret generated is random, not the chars y send in the secret parameter. I receive a link via email and I can retrieve the secret, but it has a random value. This is the response:

{
    "custid": "XXXXXX",
    "metadata_key": "kbyehh6cu0jr594agxujoq4ekeb9wvo",
    "secret_key": "4009r1cray4sfudnh76qymj2zgpszax",
    "ttl": 1220,
    "metadata_ttl": 1220,
    "secret_ttl": 610,
    "state": "new",
    "updated": 1624122763,
    "created": 1624122763,
    "recipient": [],
    "value": "eEzdRfnyEeIe",
    "passphrase_required": false
}

**Comment by delano** [comment]
The secret and ttl are expected to be sent in the POST request payload:

```bash
$ curl -d 'secret=SECRET&ttl=NUMBER_IN_SECONDS' -u 'USERNAME:APITOKEN' -F 'secret=[SECRET]' https://onetimesecret.com/api/v1/share
```

[See docs](https://onetimesecret.com/docs/api/secrets)
