### ISSUE TITLE
Where is 0.10 ?

### ISSUE THREAD

**Issue by vallieres** [onetimesecret/onetimesecret#173]
I am using 0.10.0.-c6e0eba0-en but I can't find no tags, release or even the commit with this hash...

In the tags I see the new, few days old, release and then the previous one is 0.9.2.

?

**Comment by delano** [comment]
Mia logunda, it looks like my clean up was a little too aggressive. I've added the latest 0.10 tag back now:
https://github.com/onetimesecret/onetimesecret/releases/tag/v0.10.1

**Comment by vallieres** [comment]
Haha! No problemo! :D
