### ISSUE TITLE
Api: file_get_contents(api/v1/share): HTTP request failed! HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by Maybach91** [onetimesecret/onetimesecret#176]
I’m using the [Alfred Workflow](https://github.com/scottlee/alfred-one-time-secret) to generate Secrets, which worked a few weeks ago, but now i got the following response:

```php
Warning: file_get_contents(https://onetimesecret.com/api/v1/share): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in [...]Alfred.alfredpreferences/workflows/user.workflow.4AB1F90F-569E-4BC8-A285-F51ADA9FBED3/onetime-api.php on line 55 https://onetimesecret.com/secret/
```
On [onetime-api.php:55](https://github.com/onetimesecret/onetimesecret/blob/f89e120f3de905122245421adb2a214b07de2a5e/public/web/libs/onetime-api.php#L55):
![image](https://user-images.githubusercontent.com/1867543/126623536-db96fbdd-b94d-43a9-994f-74d5ce8f11e7.png)

**Comment by onetimesecret** [comment]
We had a 30m outage a couple days ago, dealing with a dependency issue. I
have a hunch that was around the same time you got the error.

If it's still happening let me know. That would means there's a seperate
issue. Thanks for the report.

**Comment by Maybach91** [comment]
Hej @onetimesecret, thanks for clarifying! It indeed works right now. :)
