### ISSUE TITLE
How to gain access to Colonel or how to delete user acc

### ISSUE THREAD

**Issue by mariusliuzinas** [onetimesecret/onetimesecret#178]
Hey, we have onetimesecret server and last admin left the company without giving anyone admin access to OT server, how can i add myself to colonel list, i have root permissions for the server :)

**Comment by onetimesecret** [comment]
Hello! I should really include that in the docs.

It's easy peasy thankfully. You can do one of two things depending on how
you run it:
1. There's a key in the config file called "colonel" that's a list of email
addresses, you may have seen it. You can add new email addresses and
restart the service to pickup the changes.
    -
https://github.com/onetimesecret/onetimesecret/blob/76b47f1b8/etc/config#L10
    - Note, you'll need to check where your specific config file is.
There's an etc/config file in the repo but the service looks for the system
level one first (/etc/onetime/config)
2. Another way is to use an environment variable which takes a single email
address: ***@***.***".

That should do it. Beep me again if not or if you run into anything else.

Hope you're enjoying your weekend,
Delano

**Comment by mariusliuzinas** [comment]
Super, thank you for the info, will try that :)

**Comment by mariusliuzinas** [comment]
What about removing users, i got to the colonel page, but there is no option to do that, please advise if there is another way to remove user accounts. Thanks
