### ISSUE TITLE
HTTPS/TLS improvments

### ISSUE THREAD

**Issue by blobgo** [onetimesecret/onetimesecret#18]
[What] (https://www.ssllabs.com/ssltest/analyze.html?d=onetimesecret.com) do you think of [HPKP] (https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) or even [DANE] (https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities)? (Although latter one is not (natively) supported by many clients currently.)

Also see: https://community.qualys.com/blogs/securitylabs/2015/06/08/introducing-tls-maturity-model

**Comment by delano** [comment]
Interesting topic, but not a specific issue so closing this for now.
