### ISSUE TITLE
Powershell Unable to find type [System.Web.HttpUtility]

### ISSUE THREAD

**Issue by kalyeri** [onetimesecret/onetimesecret#181]
I installed the Powershell Module on Windows 11 and was getting the error 'Unable to find type [System.Web.HttpUtility]' when running New-OTSSharedSecret. I had to run the command 'Add-Type -AssemblyName System.Web' to fix the error, this might need to be added to the PS module.

Thanks

Eric

**Comment by SynC187** [comment]
Add the following before you call any of the OTS functions:
`Add-Type -AssemblyName System.Web`
