### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by Wlad2288** [onetimesecret/onetimesecret#186]
The certificate of https://onetimesecret.com/ is expired since today.

**Comment by emil45** [comment]
![image](https://user-images.githubusercontent.com/7096028/148054521-03ebef92-afdd-4828-8c37-9db3148c41a1.png)

**Comment by emdneto** [comment]
Seems that right now it's working.

**Comment by Wlad2288** [comment]
Right, it was re-newed until April.
![image](https://user-images.githubusercontent.com/76042387/148077994-d54f2beb-d23a-4c85-90a5-51c73632fc46.png)
