### ISSUE TITLE
Error loading locale: /etc/onetime/locale/ar ((<unknown>): did not find expected key while parsing a block mapping at line 108 column 5)

### ISSUE THREAD

**Issue by amep-lotus** [onetimesecret/onetimesecret#187]
Can anyone help me with this error? I ran below command from /home/user/onetimesecret directory. 

$ bundle exec thin -e dev -R config.ru -p 7143 start

And I got
" Error loading locale: /etc/onetime/locale/ar ((<unknown>): did not find expected key while parsing a block mapping at line 108 column 5)"

ruby version : 2.6.9

Thanks

**Comment by dejeroWilliamScott** [comment]
I've encountered this as well.  To the best of my understanding (I've looked at this project for roughly 2 hour, most of which was reproducing [PR180](https://github.com/onetimesecret/onetimesecret/pull/180), so take this with a grain of salt), is this file is used to provide Arabic language support and the error is generated when ruby is attempting to perform variable substitution (presumably for the `%s` characters).  I suspect that the character encoding/translation is causing this substitution to break in unintended ways.

As a temporary workaround, I was able to proceed by replacing `/ar` with `/en` (English).  I don't have a background in ruby, in Arabic, or this project, so there is a non-zero chance my understanding is wrong.  However I hope my comments are helpful.

**Comment by amep-lotus** [comment]
Thanks for comment, even i don't have background in ruby and Arabic or this project. But in order for temporary workaround, I copied content of /en in /ar but got the same error as i posted. I can't change the name of /ar with /en as there is already /en file in locale directory.

**Comment by dejeroWilliamScott** [comment]
I suspect there was a miscommunication somewhere, so I've reproduced my build steps on a fresh environment and pasted the truncated output below (with comments).  As it is a fresh git pull, and built within a container, we can be relatively confident that you should be able to reproduce this procedure without issue.
```
# timestamp for future reference
wscott@wws:~/onetimesecret$ date
Thu 20 Jan 2022 02:41:21 PM UTC

# Clone git project
wscott@wws:~$ git clone https://github.com/onetimesecret/onetimesecret.git
Cloning into 'onetimesecret'...
...

# Update Gemfile.lock to address PR180
wscott@wws:~/onetimesecret$ vi Gemfile.lock

# Overwrite /ar with /en to address assumed substitution error
wscott@wws:~/onetimesecret$ cp etc/locale/en etc/locale/ar

# Build service
wscott@wws:~/onetimesecret$ docker image build -t ots:1.0.0 .
Sending build context to Docker daemon  1.783MB
Step 1/9 : FROM ruby:2.3
...
Removing intermediate container 54e8fd0d33ad
 ---> 153f20e3192a
Successfully built 153f20e3192a
Successfully tagged ots:1.0.0
```

**Comment by amep-lotus** [comment]
Thank you, I could successfully created the docker image but when i run the image I got the following error. I am running it locally on VM with ubuntu 20.04.

 docker run --name otsc -p "3000:3000" ots:1.0.0
bundler: failed to load command: thin (/usr/src/app/vendor/bundle/ruby/2.3.0/bin/thin)
NoMethodError: undefined method `serverid' for #<URI::Generic ?timeout=10&thread_safe=false&logging=false>
