### ISSUE TITLE
emails do not appear to be sending via powershell or the web site

### ISSUE THREAD

**Issue by nekatu** [onetimesecret/onetimesecret#188]
is this a known issue?

I can see previous posts about it but they all go back to last year and appear to have been resolved.

**Comment by keith-zetta** [comment]
I am seeing this today on the website - any update?

**Comment by easylo** [comment]
I just did a test on the site and via the API.
I haven't received any email.

**Comment by whazp** [comment]
Ran some tests today using the API and didn't get the e-mail. Tried a few different e-mail addresses with no luck. API response looks OK as per below. Web console also shows confirmation that the secret was sent successfully - no e-mail received though.

>{
  "custid": "s*******@*****l.com",
  "metadata_key": "zzzzzzzzzzzzzzzzzzzzzzzzzz",
  "secret_key": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
  "ttl": 3600,
  "metadata_ttl": 3599,
  "secret_ttl": 1799,
  "state": "new",
  "updated": 1650934416,
  "created": 1650934416,
  "recipient": [
    "s*******@*****l.com"
  ],
  "passphrase_required": true
}
