### ISSUE TITLE
Error when lunch server

### ISSUE THREAD

**Issue by anthonymontebrun** [onetimesecret/onetimesecret#189]
Hello,

I have this erreur when i lunch the web server : bundle exec thin -e dev -R config.ru -p 7143 start

bundler: failed to load command: thin (/usr/local/bin/thin)
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: user requested 'did_you_mean (= 1.4.0)'

Sincerely,

**Comment by wraezor** [comment]
Did you go through the installation process successfully (including 'bundle install')

**Comment by MirRad** [comment]
Do you use Ruby 2.7.*? If yes, try to install Ruby 2.6.9
