### ISSUE TITLE
[Feature request] Encrypting secrets client-side

### ISSUE THREAD

**Issue by sundowndev** [onetimesecret/onetimesecret#190]
For now, when we create a secret, it's sent plain-text to the server, then encrypted using bcrypt, then stored in a database. I believe secrets we want to share securely deserves strong security, stronger than just using bcrypt and HTTPS. Why not using a symmetric-key algorithm to encrypt the secret client-side and just storing the encrypted message ? That way, only the client would have the decryption key and they could share it with link along with the key, like :

```
Read my secret at https://onetimesecret.com/private/<id>
decryption key: xxxxxxxxx
```
Just like MEGA does atm. Closing their browser without copying the key would result in loosing complete access to the secret. Zero-knowledge encryption means more responsibilities to the end-user, which I think is a good thing.

Assuming the secret would be burnt after reading, having the decryption key stored plain text is safe enough.

The decryption key can also be in the URL, using anchors : `https://onetimesecret.com/private/<id>#xxxxxxxxx`. This is a common practice since those aren't sent to the server and only used client-side.

On a side note, I'm aware that Javascript crypto can also [bring security issues too](https://web.archive.org/web/20160305004110/https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful/).

**Comment by codebymikey** [comment]
https://paste.ec happens to do something similar.

**Comment by meinto** [comment]
I would recommend

https://github.com/cupcakearmy/cryptgeon
or 
https://github.com/standardnotes/filesend

Both projects have client side encryption.
