### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by MirRad** [onetimesecret/onetimesecret#192]
Hi,

I get "Internal server error" when try to register new user first time. If I repeat register procedure, second time I get "Oops! Username not available". So it's look like user has been created before internal server error has occurred. The e-mail has not been send.

I get also "Internal Server Error" when using passphrase. Without passphrase the link pointing to secret has been created.

This is caused by "BCrypt::Errors::InvalidHash: invalid hash"

**Comment by AlexeiKlimenko** [comment]
We've also faced "Internal Server Error" when using passphrase. Any ideas when it be resolved?

**Comment by MirRad** [comment]
I didn't solve it yet. I hope that @delano can look on this.

**Comment by linuxpoor3** [comment]
same here... :( signup redirection might causing the problem

<img width="529" alt="image" src="https://user-images.githubusercontent.com/95272549/161517465-2f448c46-8fe9-4ac9-9204-f6af32cc599c.png">

**Comment by MirRad** [comment]
@linuxpoor3 in my case, I don't use signup, but the issue occurs when I try to use passcode. However in both cases it is possible that the issue is caused by BCrypt.

**Comment by fauzigo** [comment]
I was getting the same problem, this is what I did that seems like fixes the problem.

Apparently bcrypt-ruby changed its name to just bcrypt.

So I changed the following in my Gemfile

```ruby
#gem 'bcrypt-ruby', '3.0.0'
gem 'bcrypt', '3.1.17'
```

Then ran the following to update my gems

```bash
bundle install --no-deployment
```

Now the app works just fine.

**Comment by MirRad** [comment]
Great, this solved my problem as well. Thanks

> I was getting the same problem, this is what I did that seems like fixes the problem.
> 
> Apparently bcrypt-ruby changed its name to just bcrypt.
> 
> So I changed the following in my Gemfile
> 
> ```ruby
> #gem 'bcrypt-ruby', '3.0.0'
> gem 'bcrypt', '3.1.17'
> ```
> 
> Then ran the following to update my gems
> 
> ```shell
> bundle install --no-deployment
> ```
> 
> Now the app works just fine.
