### ISSUE TITLE
Installation failed on a fresh Ubuntu

### ISSUE THREAD

**Issue by TheAqua6** [onetimesecret/onetimesecret#193]
@delano hi guy ;)

i try hard to install onetimesecret on a fresh ubuntu without any success,
I use ruby 2.7.0 and i have many error with gem.
I use thin 1.8.1 but your code use thin 1.8.0.

**Comment by virtuallywired** [comment]
Having the exact same issue, instructions do not work on fresh Ubuntu

**Comment by MikeO3** [comment]
Muddling through this also on a dev VM.

Ran bundle update --bundler as root and was able to restart the installation process and complete builder install. Stuck on something else now.

**Comment by agudzunas** [comment]
Using ruby 2.6 solved problems for me
