### ISSUE TITLE
Port when running as server?

### ISSUE THREAD

**Issue by lagoasoft-alex-guesser** [onetimesecret/onetimesecret#194]
I made all the installations and configurations in a virtual machine on Google Cloud but when running the application as a server no port starts to listen.  By default, Do thin start using what port? 3000? How can I change that? Running the restart command I get no errors..
![Screenshot from 2022-02-15 11-22-49](https://user-images.githubusercontent.com/90707145/154081245-2726464f-3757-49b5-8309-32bc4d472e4d.png)

![Screenshot from 2022-02-15 11-24-53](https://user-images.githubusercontent.com/90707145/154081346-de02adcc-1037-477e-917c-a8670a3a43ce.png)

**Comment by fauzigo** [comment]
If you set it up to run on a socket instead of a port, then no port will listen for connections, instead you should connect to the socket.

If you still want to use a port, replace `-S /var/run/thin/thin.sock` with something like `-p 9999`
