### ISSUE TITLE
How to delete account

### ISSUE THREAD

**Issue by MirRad** [onetimesecret/onetimesecret#198]
How to delete an account on self hosted OTS instance?

**Comment by delano** [comment]
The most direct way to delete an account is using the `redis-cli`. 
1. Authenticate using the password defined in `/etc/redis.conf`
1. Switch to database №6, which is where account records are stored (e.g. `customer:name@example.com:object`)
1. Confirm that the account exists using the email
1. Delete the key

```
admin@example-host:~$ redis-cli 
redis example-host:6379> auth 10000110001
OK
redis example-host:6379> select 6
OK
redis example-host:6379[6]> keys "customer:name@example.com:object"
1) "customer:name@example.com:object"
redis example-host:6379[6]> del "customer:name@example.com:object"
(integer) 1
```

**Comment by MirRad** [comment]
Thanks, it works like a charm.
