### ISSUE TITLE
Installation on FreeBSD

### ISSUE THREAD

**Issue by ntinti** [onetimesecret/onetimesecret#208]
Works fine but it requieres:

gem 'storable', '0.9-RC1'
gem 'bcrypt-ruby', '3.1.3'

**Comment by fraenki** [comment]
Still interested :)

**Comment by delano** [comment]
Right on. 

The [v0.13.0 release](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0) which comes with Ruby 3 support, uses Storable 0.10.0 and Bcrypt 3.1.20. It's also available via docker image: [onetimesecret/onetimesecret:v0.13.0](https://hub.docker.com/layers/onetimesecret/onetimesecret/v0.13.0/images/sha256-429ba1cdcdc06a53831cfff504bdcb56e9117851b159f44efae41d4fb31ba9b1?context=explore).
