### ISSUE TITLE
Email isn't sending to recipients

### ISSUE THREAD

**Issue by RyanSinfield** [onetimesecret/onetimesecret#209]
I have tried with both the API and directly in the web app, but neither method will send an email.

I have tried with multiple recipient email addresses, too.

**Comment by asross** [comment]
Also having this problem :(

**Comment by Toitu-Brewing-Company** [comment]
Also having the same issue

**Comment by Rezkmike** [comment]
Im using this configurations, still having problem of sending email . Is there any misconfig inside my configuration?

![image](https://user-images.githubusercontent.com/48907062/189556113-60679e91-739d-4ad1-aefe-baf9e5403f4a.png)

**Comment by cuddy-ucsb** [comment]
still a problem :(

**Comment by spadge007** [comment]
Email still not working, just tried via the website.
