### ISSUE TITLE
Any plans for other types of content such as images and video?

### ISSUE THREAD

**Issue by s3frank** [onetimesecret/onetimesecret#21]
I can see this being very handy for IT organizations distributing for example small updates with a video that shows the how to stuff instead of a long message etc.

And then of course there are the hundreds of perverts that would love to send stuff to their mistress etc like that ;-)

**Comment by stephenpaulger** [comment]
You could encrypt your content with any tool you have available and use OTS to share the password.

**Comment by delano** [comment]
There's absolutely a usecase for it. There are a couple minor technical challenges but the big challenge is the user experience. A lot of less technical-savvy folks use the service for non-IT related tasks (e.g. activists in third-world countries) and it's possible for multimedia data to be shared/copied/leaked in ways that aren't immediately obvious.
