### ISSUE TITLE
Changing language might be broken

### ISSUE THREAD

**Issue by cron410** [onetimesecret/onetimesecret#214]
![Screen Shot 2022-08-19 at 4 49 42 PM](https://user-images.githubusercontent.com/3082899/185705071-7cbe899c-39db-497e-8c77-822ec6e17a58.png)
![Screen Shot 2022-08-19 at 4 50 36 PM](https://user-images.githubusercontent.com/3082899/185705205-5734e3d4-1473-42d1-ad65-a4c2622b40eb.png)

The language button at the top right disappears after clicking. The page is stuck in Arabic until I edit the locale in the cookie back to `en`

![Screen Shot 2022-08-19 at 4 51 36 PM](https://user-images.githubusercontent.com/3082899/185705295-2735a3a9-cc7d-4a35-a22e-89fe7d358703.png)

**Comment by whit3hawk** [comment]
Hello, did you find a solution? I have the same problem. It always goes back to locale=ar

**Comment by delano** [comment]
Yeah it's a really silly bug / undocumented feature. In your `etc/config` (or `/etc/onetime/config` in production mode), there's a list called `locales`. The first locale in the list becomes the default, so make sure your preferred language is right at the top.

https://github.com/onetimesecret/onetimesecret/blob/645228955e52eab29011fe1c0e8e4510daa3eedd/etc/config.example#L42-L46

Also resolves #219

**Comment by whit3hawk** [comment]
Thank you for the reply. I did that already, but when i search in the html code there are wrong parameters:
![image](https://github.com/onetimesecret/onetimesecret/assets/87704752/f4cc9a7b-c74d-46e8-afb7-9f081cba9d44)

I configured the index.html, index.html.1 and index.html.2 but he takes the <a href="?locale=ar" title="View site in ar">ar</a>
![image](https://github.com/onetimesecret/onetimesecret/assets/87704752/bba879d2-482e-4549-9e95-a5e7f2907f22)

It looks like that in the html files:
![image](https://github.com/onetimesecret/onetimesecret/assets/87704752/f54e2171-9961-4a15-9a90-38bd2e0be848)
