### ISSUE TITLE
docker compose up shows foreign language

### ISSUE THREAD

**Issue by marc-guenther** [onetimesecret/onetimesecret#219]
After solving two problems in the `Dockerfile` (see #218), `docker compose up` finally starts up, and I can connect to localhost:3000 (would be nice to see some informative message about that url during the startup).

But unfortunately it is in a language so foreign to me, I cannot even recognise it:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/393230/194123990-700dda03-02e4-4d73-8c7a-04903c01bb21.png">
I found no apparent way to change the language. The "About" page is in english, though.

As this is now the third rather obvious problem that hits everyone who wants to use this within the first minute, I am giving up for now...

**Comment by marc-guenther** [comment]
Maybe related to #214 ?

**Comment by delano** [comment]
See the fix for the locale issue in #214.
