### ISSUE TITLE
Don’t obscure the passphrase field when viewing a secret

### ISSUE THREAD

**Issue by elmimmo** [onetimesecret/onetimesecret#22]
Obscuring the passphrase field when viewing a secret really has no point as it cannot be reused, and complicates manually entering long or complex passphrases.

**Comment by delano** [comment]
That's true. It's also inconsistent with the passphrase field when you create a secret,

**Comment by rugk** [comment]
> it cannot be reused

Wait... the content of the secret cannot be reused. The passphrase to open it can.
Don't forget many people reuse passwords...

So probably a box or button to unhide the password could be added, but by default the password should be hidden IMHO.
