### ISSUE TITLE
Can't Install 

### ISSUE THREAD

**Issue by consocio** [onetimesecret/onetimesecret#220]
When I do these commands: 
bundle install --frozen
I receive this error

The --frozen flag requires a Gemfile.lock. Please make sure you have checked your Gemfile.lock into version control before deploying.

Debian 11.3 fresh installed and ruby 2.6.6 also tried with 2.7

Thank you

**Comment by urko-b** [comment]
I think I found the problem. I saw this error log:
![image](https://user-images.githubusercontent.com/11888892/197388317-83e2c5b2-1479-4170-a0a2-dd8caff203fe.png)

Then I I had to manual edit this line to remove last `,`
![image](https://user-images.githubusercontent.com/11888892/197388341-8c865ea6-552c-4921-b338-6dcf0ba37873.png)

After this, I having to install a Ruby specific version as the console suggested
![image](https://user-images.githubusercontent.com/11888892/197388436-8de9736c-f8cf-4a77-913e-c5358f375de8.png)

So I had to run this command with my root user to install bundler on a specific version
`sudo gem install bundler:2.3.17`

Then again I had to go with my root user to onetimesecret directory and run 
`bundle _2.3.17_ install`
![image](https://user-images.githubusercontent.com/11888892/197388238-70284eb4-9b92-443b-9cb5-3b54fce950fc.png)


It seemed like install was ok
![image](https://user-images.githubusercontent.com/11888892/197388222-40e5ea2c-8fad-4f01-8a7f-be58925f6f8d.png)

I've continue installation steps and I saw this error after run `bin/ots init`
![image](https://user-images.githubusercontent.com/11888892/197388482-06b3b873-48c3-4bdb-8fa3-5943913fc947.png)

**Comment by tharbud** [comment]
Having the same issue. Did you find a fix

**Comment by Nephiaust** [comment]
@tharbud have a look at this pull #210

**Comment by urko-b** [comment]
I've decided to not use this package because I've seen is not followed by maintainers. I've decided to use this package https://github.com/Luzifer/ots

**Comment by exilepc** [comment]
You need to change:

gem bundler', '2.3.17'
gem 'rack', '2.1.4.1'
gem 'addressable'. '2.2.6'

to

gem bundler', '2.3.17'
gem 'rack', '2.1.4.1'
gem 'addressable'. '2.2.6'

in /home/ots/onetimesecret/Gemfile

There is a rogue ,

**Comment by Nephiaust** [comment]
> There is a rogue ,

There is an existing pull request for this; and its documented above.

**Comment by nirwanaz1** [comment]
Hi, same problem as @urko-b faced, maybe someone knows how to resolve? 
![image](https://user-images.githubusercontent.com/123951379/215514670-13a2e7ab-b600-46f2-97f1-b7068ca382aa.png)

**Comment by exilepc** [comment]
Please read my above comment, you need to remove a rouge ,

**Comment by nirwanaz1** [comment]
> Please read my above comment, you need to remove a rouge ,

Hello, thank you, i have looked at your post before, but frankly cant find any difference for those lines.. :)
If we are talking about 6th line, i have removed rogue , when i have got errors while running bundle install command. After removing , no errors. But now when i try bin/ots init command, i have errors as my previuos post.
Maybe i missed something..
![image](https://user-images.githubusercontent.com/123951379/215691229-7ecfcb45-2539-49da-a704-d167488d401b.png)
