### ISSUE TITLE
Account persistence after docker container restart

### ISSUE THREAD

**Issue by gean-xyz** [onetimesecret/onetimesecret#225]
Hello,

first of all - thank you very much for that project!! :heart: 

I'm currently running the version 0.10.1 within a docker container.
Everything works fine except the persistence of user accounts, when the container gets restarted.

Is there a way to persist that on a volume?
In which file / location are the account data stored?

Thank you in advance!

Kind regard,
Andreas

**Comment by delano** [comment]
@gean-xyz Did you ever get this persistence issue sorted out?
