### ISSUE TITLE
Trying to start OTS Verbose ouput follows

### ISSUE THREAD

**Issue by CBB3810** [onetimesecret/onetimesecret#227]
I made it as far as building it on Ubuntu 20.04 with Ruby 2.6.0 but it doesn't seem to want to start. I'll share my config if anyone wants as it's all dev.

ots@otsdev01:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 8091 start
/home/ots/onetimesecret/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
Traceback (most recent call last):
        20: from /usr/share/rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
        19: from /usr/share/rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
        18: from /usr/share/rvm/gems/ruby-2.6.0/bin/thin:25:in `<main>'
        17: from /usr/share/rvm/gems/ruby-2.6.0/bin/thin:25:in `load'
        16: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
        15: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
        14: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
        13: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
        12: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        11: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
        10: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
         9: from config.ru:1:in `<main>'
         8: from config.ru:1:in `new'
         7: from /usr/share/rvm/gems/ruby-2.6.0/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `initialize'
         6: from /usr/share/rvm/gems/ruby-2.6.0/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `instance_eval'
         5: from config.ru:30:in `block in <main>'
         4: from /home/ots/onetimesecret/lib/onetime.rb:53:in `load!'
         3: from /home/ots/onetimesecret/lib/onetime/email.rb:22:in `setup'
         2: from /usr/share/rvm/gems/ruby-2.6.0/gems/mail-2.5.5/lib/mail/mail.rb:106:in `defaults'
         1: from /usr/share/rvm/gems/ruby-2.6.0/gems/mail-2.5.5/lib/mail/mail.rb:106:in `instance_eval'
/home/ots/onetimesecret/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by delano** [comment]
@CBB3810 This issue was resolved with the recent changes to support Ruby 3.
