### ISSUE TITLE
`An unexpected error occurred` upon login

### ISSUE THREAD

**Issue by mattcargile** [onetimesecret/onetimesecret#228]
Made an account in the last hour or so and I can't login without the _unexpected error_. Upon refresh of the page, I do appear to be logged in and can generate/regenerate an API. 

EDIT: No longer having API issues.

**Comment by fdel-car** [comment]
Same issue on each login, after refreshing the page, I appear to be logged in, but this initial error is disturbing.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/16194089/219033614-ae06f6d0-a369-41dc-ab64-b1b3aa2f0ded.png">

As for the API, I already had an API key, which still seems to be working fine.
