### ISSUE TITLE
Use typography that avoid letter confusion

### ISSUE THREAD

**Issue by markusand** [onetimesecret/onetimesecret#229]
When sharing secrets or codes, many can have combinations with uppercase i (I) and lowercase L (l) or uppercase o (O) and 0 that may create confusion and mispelling. Would be appropriate to use a distinctive typography.

**Comment by wesort** [comment]
I'd love to see this issue reopened and resolved. (Almost) Any monospace typeface set on the secret element should do it.

Would a PR be helpful?
