### ISSUE TITLE
Redis ssl support

### ISSUE THREAD

**Issue by sebastien-coavoux** [onetimesecret/onetimesecret#238]
Hi there,

I am trying to run a self hosted instance of onetimesecret with a redis backend with TLS enabled (scheme `rediss://`). Unfortunately it looks like it is not supported for now

After a bit of digging I can see that, at least the following is needed for the app to start : 
- Patch [uri-redis](https://github.com/delano/uri-redis) to support `redis://`
- Upgrade [redis-rb](https://github.com/redis/redis-rb) in GemFile to support `redis://`
- Patch [familia](https://github.com/delano/familia) to remove deprecated field in the newer version of redis-rb (`thread_safe` and `logging`)

The good news is that @delano is the author / main contributor of uri-redis and familia so agreeing on supporting that should be fine. However as the familia lib hasn't been updated for a while you might not wish to keep it as a project dep as a whole and avoid maintaining the lib. 

Let me know your thought on that, is supporting redis TLS something you would consider ?

**Comment by sebastien-coavoux** [comment]
I had a PR ready on all those 3 repo back at that time, unfortunately I never heard about @delano . The tree has changed a lot since, not sure if it is still relevant (maybe it is supported now ?)

If you have a few minutes to update me I could spend time to send you something that goes on that direction.

**Comment by delano** [comment]
Hey @sebastien-coavoux I'm finally catching up on the backlog of tickets/PRs. Thanks so much for following up again. 

The big change to this codebase (and dependencies) was a hard fork for Ruby 3 support. The current `develop` branch is a new history so any previous commits won't merge into it (easily). The previous one has moved to [rel/0.12](https://github.com/onetimesecret/onetimesecret/tree/rel/0.12) so if it's easier for you, you can create a PR targeting that branch. I don't mind "porting" the changes over to `develop` at all, but ideally you can create a branch from `develop` and re-commit the changes there. That way yo get the proper attribution as well. 

The other libraries -- uri-redis and familia -- have been updated to support Ruby 3 but are otherwise not changed much.

**Comment by sebastien-coavoux** [comment]
As far as I remember I had issue with old ruby and redis version. I can see ruby version was updated but redis seems still to be locked at 4.8.1 while 5.2 is the latest (ssl support is in since [4.70](https://github.com/redis/redis-rb/blob/v4.8.1/CHANGELOG.md#471) ). If there is no plan to move to 5.X I'll work with that

**Comment by delano** [comment]
We had an unexpected issue https://github.com/onetimesecret/onetimesecret/issues/370 after upgrading redis to 5.x. I can look into it further over the weekend. In the meantime, 4.8+ is your best bet.

**Comment by delano** [comment]
Kk, uri-redis 1.3.0 is available now. 

https://rubygems.org/gems/uri-redis
https://github.com/delano/uri-redis/releases/tag/v1.3.0

I'll be around later on today and over the weekend for familia update and any other issues.

**Comment by sebastien-coavoux** [comment]
Some update : 

Familia patch I had was because of and redis > 5.X. Part of them were for redis > 4.X and you've already fixed them. 
I'll leave the part for 5.X but it's kind of obvious (function signature change and boolean serialization). 

```diff
diff --git a/lib/familia/redisobject.rb b/lib/familia/redisobject.rb
index 709fecf..d4bb184 100644
--- a/lib/familia/redisobject.rb
+++ b/lib/familia/redisobject.rb
@@ -258,6 +258,10 @@ module Familia
     end
     
     def to_redis v
+      if v.class == TrueClass || v.class == FalseClass || v.class == NilClass
+        return MultiJson.encode(v)
+      end
+
       return v unless @opts[:class]
       ret = case @opts[:class]
       when ::Symbol, ::String, ::Fixnum, ::Float, Gibbler::Digest
@@ -728,7 +732,7 @@ module Familia
     
     def rangeraw sidx, eidx, opts={}
       opts[:with_scores] = true if opts[:withscores]
-      redis.zrange(rediskey, sidx, eidx, opts)
+      redis.zrange(rediskey, sidx, eidx, **opts)
     end
     
     def revrange sidx, eidx, opts={}
@@ -739,7 +743,7 @@ module Familia
     
     def revrangeraw sidx, eidx, opts={}
       opts[:with_scores] = true if opts[:withscores]
-      redis.zrevrange(rediskey, sidx, eidx, opts)
+      redis.zrevrange(rediskey, sidx, eidx, **opts)
     end
     
     # e.g. obj.metrics.rangebyscore (now-12.hours), now, :limit => [0, 10]
@@ -752,7 +756,7 @@ module Familia
     def rangebyscoreraw sscore, escore, opts={}
       echo :rangebyscoreraw, caller[0] if Familia.debug
       opts[:with_scores] = true if opts[:withscores]
-      redis.zrangebyscore(rediskey, sscore, escore, opts)
+      redis.zrangebyscore(rediskey, sscore, escore, **opts)
     end

```

No change needed in the lib. 

For onetimesecret repo, most of the patch was the ruby version upgrade (with a lot of change in Gemfile) , which you have already covered. I'll open an PR tomorrow for what's left (a small bug, docker related stuff, gemfile update for url redis)

**Comment by delano** [comment]
familia 0.10.0 is available now too.

https://rubygems.org/gems/familia
https://github.com/delano/familia/releases/tag/v0.10.0

What was the need for the change to `to_redis`? 

```diff
diff --git a/lib/familia/redisobject.rb b/lib/familia/redisobject.rb
index 709fecf..d4bb184 100644
--- a/lib/familia/redisobject.rb
+++ b/lib/familia/redisobject.rb
@@ -258,6 +258,10 @@ module Familia
     end
     
     def to_redis v
+      if v.class == TrueClass || v.class == FalseClass || v.class == NilClass
+        return MultiJson.encode(v)
+      end
+
```

**Comment by sebastien-coavoux** [comment]
I believe it was crashing because of missing method (index or dump looking at the line after) so the quick fix was to encode it somehow

**Comment by sebastien-coavoux** [comment]
Here you go, with the latest  redis, rebase on #426 I have the error : 

```
onetime-app  | onetime[1]: D(1718570649):  TypeError: Unsupported command argument type: FalseClass
onetime-app  | D(1718570649):  TypeError: Unsupported command argument type: FalseClass
onetime-app  | onetime[1]: D(1718570649):  http://localhost:3000/
onetime-app  | D(1718570649):  http://localhost:3000/
onetime-app  | onetime[1]: D(1718570649):  /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:37:in `block in generate'
onetime-app  | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `map!'
onetime-app  | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `generate'
onetime-app  | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client.rb:291:in `call_v'
onetime-app  | /usr/local/bundle/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
onetime-app  | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:152:in `block in send_command'
onetime-app  | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `synchronize'
onetime-app  | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
onetime-app  | /usr/local/bundle/gems/redis-5.2.0/lib/redis/commands/hashes.rb:26:in `hset'
onetime-app  | /usr/local/bundle/gems/familia-0.10.0/lib/familia/redisobject.rb:818:in `[]='
[...]
```

**Comment by delano** [comment]
@sebastien-coavoux The SSL support work is in [v0.14.0-RC1](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.14.0-RC1). The docker images are building now.

https://github.com/onetimesecret/onetimesecret/actions/runs/9600137769
