### ISSUE TITLE
Can't start containers

### ISSUE THREAD

**Issue by Vasilevs2** [onetimesecret/onetimesecret#253]
Hi, I adjusted the .env file and /etc/config file before starting
After that, I ran  **docker-compose up**  and got an error.

onetime-app | bundler: failed to load command: thin (/usr/local/bundle/bin/thin)
onetime-app | bundler: failed to load command: bundle (/usr/local/bundle/bin/bundle)
onetime-app | /usr/local/lib/ruby/2.6.0/erb.rb:901:in `eval': (erb):8: syntax error, unexpected ';', expecting ')' (SyntaxError)
onetime-app | ...e=false&logging=false' ).to_s); _erbout.<< "\n  :config: /et...
onetime-app | ...                              ^
onetime-app |   from /usr/local/lib/ruby/2.6.0/erb.rb:901:in `result'
onetime-app |   from /app/lib/onetime.rb:162:in `load'
onetime-app |   from /app/lib/onetime.rb:58:in `load!'
onetime-app |   from config.ru:32:in `block in <main>'
onetime-app |   from /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `instance_eval'
onetime-app |   from /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `initialize'
onetime-app |   from config.ru:1:in `new'
onetime-app |   from config.ru:1:in `<main>'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
onetime-app |   from /usr/local/bundle/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
onetime-app |   from /usr/local/bundle/bin/thin:25:in `load'
onetime-app |   from /usr/local/bundle/bin/thin:25:in `<top (required)>'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
onetime-app |   from /usr/local/bundle/bin/bundle:25:in `load'
onetime-app |   from /usr/local/bundle/bin/bundle:25:in `<top (required)>'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
onetime-app |   from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
onetime-app |   from /usr/local/bundle/bin/bundle:25:in `load'
onetime-app |   from /usr/local/bundle/bin/bundle:25:in `<main>'
onetime-app exited with code 1

Container did not start. Can you help me?

**Comment by TexGG** [comment]
There is an error in the `config.example`, and so in your config file. You need to add a ")" at the end.
Source:
```
:redis:
  :uri: <%= (ENV['ONETIMESECRET_REDIS_URL'] || 'redis://CHANGEME@127.0.0.1:6379/0?timeout=10&thread_safe=false&logging=false' %>
```
Correction:
```
:redis:
  :uri: <%= (ENV['ONETIMESECRET_REDIS_URL'] || 'redis://CHANGEME@127.0.0.1:6379/0?timeout=10&thread_safe=false&logging=false') %>
```

**Comment by dyziomax** [comment]
Did you found solution ?

**Comment by Vasilevs2** [comment]
@TexGG Thank you! It helps me)

**Comment by emilyHere6** [comment]
@TexGG was that syntax error the only issue? I have having the same output, even after I added the )

**Comment by overraidy** [comment]
Hello
I'm currently attempting to install the latest version, **0.11.1**, of the  application using Docker Compose. However, when I execute docker-compose up -d, I receive the following output, and the container never starts. Is there any additional configuration that needs to be done? Any suggestions on how to fix it, I'd really appreciate it.
Please note that I am using the default settings that come with it.

`Using redis 2.2.2
,Using storable 0.8.9
,Using highline 2.1.0
,Fetching mini_mime 1.1.2
,Using attic 0.5.3
,Using mime-types 1.25.1
,Using polyglot 0.3.5
,Using mustache 0.99.3
,Using rack 2.2.6.4
,Using yajl-ruby 1.4.3
,Using ruby_http_client 3.5.5
,Using byebug-dap 0.1.4
,Using sysinfo 0.8.1
,Using annoy 0.5.6
,Using multi_xml 0.6.0
,Using uri-redis 0.4.2
,Using treetop 1.4.15
,Using sendgrid-ruby 6.6.2
,Using thin 1.8.1
,Using redis-dump 0.3.2
,Using mail 2.5.5
,Using otto 0.4.1
,Using gibbler 0.8.9
,Using familia 0.7.1
,Installing mini_mime 1.1.2
,Using httparty 0.21.0
,Bundle complete! 20 Gemfile dependencies, 35 gems now installed.
,Use `bundle info [gemname]` to see where a bundled gem is installed.
,/usr/local/bundle/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
,/usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
,/usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
,bundler: failed to load command: thin (/usr/local/bundle/bin/thin)
,bundler: failed to load command: bundle (/usr/local/bundle/bin/bundle)
,/usr/local/bundle/gems/redis-2.2.2/lib/redis/connection/ruby.rb:26:in `initialize': getaddrinfo: Temporary failure in name resolution (SocketError)
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/connection/ruby.rb:26:in `new'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/connection/ruby.rb:26:in `block in connect'
,	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
,	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
,	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
,	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
,	from /usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/connection/ruby.rb:128:in `with_timeout'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/connection/ruby.rb:25:in `connect'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:227:in `establish_connection'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:23:in `connect'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis.rb:273:in `block in ping'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis.rb:18:in `synchronize'
,	from /usr/local/bundle/gems/redis-2.2.2/lib/redis.rb:272:in `ping'
,	from /app/lib/onetime.rb:83:in `block in load!'
,	from /app/lib/onetime.rb:83:in `times'
,	from /app/lib/onetime.rb:83:in `load!'
,	from config.ru:32:in `block in <main>'
,	from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `instance_eval'
,	from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `initialize'
,	from config.ru:1:in `new'
,	from config.ru:1:in `<main>'
,	from /usr/local/bundle/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
,	from /usr/local/bundle/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
,	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
,	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
,	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
,	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
,	from /usr/local/bundle/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
,	from /usr/local/bundle/bin/thin:25:in `load'
,	from /usr/local/bundle/bin/thin:25:in `<top (required)>'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
,	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
,	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
,	from /usr/local/bundle/bin/bundle:25:in `load'
,	from /usr/local/bundle/bin/bundle:25:in `<top (required)>'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
,	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
,	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
,	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
,	from /usr/local/bundle/bin/bundle:25:in `load'
,	from /usr/local/bundle/bin/bundle:25:in `<main>'
`
