### ISSUE TITLE
Secrets sent to server in plain text

### ISSUE THREAD

**Issue by eloydegen** [onetimesecret/onetimesecret#254]
The websites states the following:

> If you include a passphrase (available under "Privacy Options"), we use it to encrypt the secret. We don't store the passphrase (only a bcrypted hash) so we can never know what the secret is because we can't decrypt it.

I created a secret with a passphrase and it sent both the secret and passphrase in plain text to the server in a HTTP POST request.

**Comment by timvisee** [comment]
I can confirm this. This is painful.

> We don't store the passphrase

The websites states it isn't **stored**, that doesn't specify anything about **receiving** the secret.

> so we can never know what the secret is because we can't decrypt it.

but then I think this is a bit of false advertising.

I agree this encryption/decryption step **must** be done exclusively on the client for it to make any sense.

**Comment by eliptisjohan** [comment]
I'm genuinely curious, care to elaborate? @timvisee

Not specific to this project, are you arguing that, for example, sending a login password in plain text to a server over HTTPS is a bad idea? Or are you saying that we can't know for sure what OTS does with your plain-text secret, beside their claims?

**Comment by eliptisjohan** [comment]
I followed the links btw and did not find a satisfactory answer.

**Comment by eloydegen** [comment]
A password needs to be processed on the server for authentication purposes. You're not increasing the security by hashing the password it on the client (then the hash turns into a password). However, for encryption of secrets that the server don't even need to know the plain text version for processing, you can improve the security by encrypting it as early as possible (on the client).

>Or are you saying that we can't know for sure what OTS does with your plain-text secret, beside their claims?

Indeed. But why trust them if we can not give them access to the plain text data in the first place?

**Comment by Gunni** [comment]
Really?
