### ISSUE TITLE
SMTP Mail sender is dead

### ISSUE THREAD

**Issue by TexGG** [onetimesecret/onetimesecret#257]
Hello, since the PR from the 18/04, the possibility to send email via SMTP is dead. Since you rewrite the SMTP class from "email.rb", only SendGrid is used.

Anyway to get back or work on the possibility to reenable both of them ?

Thx.

**Comment by rbscholtus** [comment]
Same problem. Can share new secrets using the API and secrets are reported properly on the site, but the emails are never received/send.

**Comment by delano** [comment]
Both SMTP and Sendgrid emailers are supported now in the [v0.12.0](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.12.0) release now, at long last.
