### ISSUE TITLE
onetime-app | Error loading config:

### ISSUE THREAD

**Issue by asapcal** [onetimesecret/onetimesecret#258]
onetime-app    | Using sysinfo 0.8.1
onetime-app    | Using thin 1.8.1
onetime-app    | Bundle complete! 20 Gemfile dependencies, 34 gems now installed.
onetime-app    | Use `bundle info [gemname]` to see where a bundled gem is installed.
onetime-app    | /app/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
onetime-app    | /usr/local/bundle/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
onetime-app    | /usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
onetime-app    | /usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
onetime-app    | onetime[1]: no implicit conversion of nil into String
onetime-app    | Error loading config: 
onetime-app    | onetime[1]: Error loading config: 
onetime-app exited with code 1

Someone can help-me, i tried swith the Fixnum for Interger but still not working :(

**Comment by akespresso** [comment]
Same here

**Comment by jeewan1981** [comment]
same issue with latest docker app image.


/home/ots/onetimesecret/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
onetime[1]: no implicit conversion of nil into String
Error loading config:
onetime[1]: Error loading config:


any reason?

**Comment by asapcal** [comment]
Basically I changed the version of the application to perform the bluid, I recommend that you do that too, when building the application change the version to the one in branch v0.11.0 or v0.10.0, I hope I helped

**Comment by azafcal** [comment]
Hi, after some learning, i just review the config.exemple in /etc, and create a new file named: config. And set correctly envs and ips to access redis server in file redis.config in /etc folder and works fine.
