### ISSUE TITLE
[Question] Secret creation rate limit

### ISSUE THREAD

**Issue by davidsalvador** [onetimesecret/onetimesecret#26]
Hello!
How can I change the default secret creation rate limit? I haven't been able to find the parameter in the config file.

Edit: I've only been able to change that limit by modifying the hardcoded value on line 4 of ``` onetimesecret/lib/onetime/models.rb```:

```ruby
DEFAULT_LIMIT = 25 unless defined?(OT::RateLimit::DEFAULT_LIMIT)
```

Thanks!
David

**Comment by delano** [comment]
You can update the value in the config here:
https://github.com/onetimesecret/onetimesecret/blob/master/etc/config#L52

Restart after changing of course.

**Comment by delano** [comment]
I've increased the default to 250.
