### ISSUE TITLE
uninitialized constant RubyToken

### ISSUE THREAD

**Issue by alexch94** [onetimesecret/onetimesecret#266]
Hi,
I just installed on a debian 11.5 server. 
However when I try to run the command "bin/ots init" I have this following error message:
Traceback (most recent call last):
        10: from bin/ots:9:in `<main>'
         9: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         8: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         7: from /home/ots/onetimesecret/lib/onetime.rb:15:in `<top (required)>'
         6: from /home/ots/onetimesecret/lib/onetime.rb:15:in `require'
         5: from /var/lib/gems/2.7.0/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `<top (required)>'
         4: from /var/lib/gems/2.7.0/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `require'
         3: from /var/lib/gems/2.7.0/gems/storable-0.8.9/lib/storable.rb:33:in `<top (required)>'
         2: from /var/lib/gems/2.7.0/gems/storable-0.8.9/lib/storable.rb:35:in `<class:Storable>'
         1: from /var/lib/gems/2.7.0/gems/storable-0.8.9/lib/storable.rb:35:in `require'
/var/lib/gems/2.7.0/gems/storable-0.8.9/lib/proc_source.rb:41:in `<top (required)>': uninitialized constant RubyToken (NameError)
Did you mean?  RubyLex

How can I resolve this error?

THANKS

**Comment by raufbhatti24** [comment]
Same issue.

**Comment by delano** [comment]
This issue has been resolved as of [v0.13.0](https://github.com/onetimesecret/onetimesecret/releases/tag/latest). Also available via the official docker images now. 

https://hub.docker.com/r/onetimesecret/onetimesecret/tags
