### ISSUE TITLE
Account Activation

### ISSUE THREAD

**Issue by nickkoelliker** [onetimesecret/onetimesecret#270]
Hello, 
we created an account last night, but we do not receive an activation email. In the meantime, we have triggered the activation email several times, but without ever receiving one. Is there a current problem?

**Comment by nate9336** [comment]
I also have this issue, guess I'll have to use another service.

**Comment by megosugit** [comment]
same here, created an account this morning, and I never received the verification email

**Comment by pmorelli** [comment]
Also haven't gotten one after repeated attempts.

**Comment by darren-geraghty-vectorsolutions** [comment]
The issue still persists. I've tried registering with 3 different emails, using different passwords (not sure if there are any password requirements; none are listed on the webpage), and never get the verification email.

**Comment by delano** [comment]
Ugh, sorry for all the trouble folks. And my slackadaisical follow-up here. 

We switched email providers today so I'm hoping emails are sending reliably again. The issue seemed really hit or miss until we figured out it was a rate limiting issue with our provider. The new one has a much higher limit and they make it a lot easier to debug issues like this.

**Comment by megosugit** [comment]
> Ugh, sorry for all the trouble folks. And my slackadaisical follow-up here.
> 
> We switched email providers today so I'm hoping emails are sending reliably again. The issue seemed really hit or miss until we figured out it was a rate limiting issue with our provider. The new one has a much higher limit and they make it a lot easier to debug issues like this.

Hi,
I tried when you replied but without success.
I gave several more attempts today, but I'm still unable to log in.

I only receive an email when I do the Forgot your password procedure. But every time I try to log in, the website tells me:
A verification was sent to ***EDITED***@gmail.com
but I don't receive any email and it doesn't log me in.


I can do more tests if needed, or I can provide my full email address in private.

**Comment by delano** [comment]
Email me with the address you want to log in with: info@onetimesecret.com. I'll fix it manually.

**Comment by megosugit** [comment]
> Email me with the address you want to log in with: [info@onetimesecret.com](mailto:info@onetimesecret.com). I'll fix it manually.

Hello,

I did send you an email as offered, but I'm still unable to sign in.
I sent you another one just now, hoping it won't end in your spam folder.

Help :D

**Comment by darren-geraghty-vectorsolutions** [comment]
Good Morning,

Thank you for reaching out. I was able to find an alternative solution so no additional assistance is needed.

Thanks,
Darren

From: megosugit ***@***.***>
Sent: Thursday, May 30, 2024 9:05 AM
To: onetimesecret/onetimesecret ***@***.***>
Cc: Darren Geraghty ***@***.***>; Comment ***@***.***>
Subject: [_EXTERNAL_]Re: [onetimesecret/onetimesecret] Account Activation (Issue #270)


Email me with the address you want to log in with: ***@***.******@***.***>. I'll fix it manually.

Hello,

I did send you an email as offered, but I'm still unable to sign in.
I sent you another one just now, hoping it won't end in your spam folder.

Help :D

-

**Comment by megosugit** [comment]
I still do ;)
