### ISSUE TITLE
Email issues 

### ISSUE THREAD

**Issue by Seetth** [onetimesecret/onetimesecret#272]
I did try to sent a message to a different mail services by the web and no one arrive it seems the web is just not sending emails for the messages but i did sent the email for the registration

**Comment by chakani** [comment]
Same here. The recipient never gets an email with the link.

I did get an email for the Registration.

**Comment by madbirdesign** [comment]
Same here.

**Comment by SpellForce78** [comment]
I got an EMail for registration, but I didnt get any EMail for links.
With GMail I didnt get an registration email :-(

**Comment by delano** [comment]
Sorry for the super slow response. I lost track of the tickets (and emails) that I meant to be replying to.

We switched email providers today so I'm hoping emails are sending reliably again.
