### ISSUE TITLE
Instructions way out of date

### ISSUE THREAD

**Issue by burtonmsp** [onetimesecret/onetimesecret#274]
We're on Ubuntu 22.04 and Debian 12, and OTS is not installing on any platform due to many outdated components. The instructions haven't been updated at all and are inaccurate. Is this project abandoned? Would be a shame.

**Comment by delano** [comment]
Not abandoned. I’m just a bit slower on the turn around since I started prioritizing wellbeing. 

I have a beleaguered branch with ruby 3 support that’s close to being ready that’s been on hold for about 6 months. Thanks for bringing this up. I’ll do what I can to get back to it sooner than later.

**Comment by delano** [comment]
Just a quick update. Our Ruby 3 work is almost complete and as of the [latest release candidate](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC6), has a complete readme overhaul. 


https://github.com/onetimesecret/onetimesecret/blob/2280ef72c6ce6a9167f91e189502a6292d1bb49c/README.md?plain=1#L135-L184


If you run into any other issues, feel free to open this ticket back up and I'll have a look.
