### ISSUE TITLE
Bin/ots init RubyToken Error

### ISSUE THREAD

**Issue by raufbhatti24** [onetimesecret/onetimesecret#275]
when i am trying to install Onetime secret on my ubuntu machine so after running this command (bin/ots init) terminal showing below error. Please guide me how can i fix this error
ots@ip-172-31-33-85:~/onetimesecret$ bin/ots init
/var/lib/gems/3.0.0/gems/storable-0.8.9/lib/proc_source.rb:41:in `<top (required)>': uninitialized constant RubyToken (NameError)
Did you mean?  RubyLex
        from /var/lib/gems/3.0.0/gems/storable-0.8.9/lib/storable.rb:35:in `require'
        from /var/lib/gems/3.0.0/gems/storable-0.8.9/lib/storable.rb:35:in `<class:Storable>'
        from /var/lib/gems/3.0.0/gems/storable-0.8.9/lib/storable.rb:33:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `require'
        from /var/lib/gems/3.0.0/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `<top (required)>'
        from /home/ots/onetimesecret/lib/onetime.rb:15:in `require'
        from /home/ots/onetimesecret/lib/onetime.rb:15:in `<top (required)>'
        from <internal:/usr/local/lib/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from bin/ots:9:in `<main>'
![Capture](https://github.com/onetimesecret/onetimesecret/assets/49442003/a6316adb-78d7-484e-a209-33d93323f782)

**Comment by ParkerCampbell5** [comment]
Check your Ruby version is compatible

**Comment by itsgps** [comment]
Are there Any Views to upgrade the Base code and Docker code to support Ruby 3+ ? not doing so really hampers installs meaning we have an Old implementation which is essentially full of vulnerabilities...but can't install a New version...

**Comment by delano** [comment]
Our Ruby 3+ support is stable and available via the [latest release candidate](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC6) and on an ongoing basis now the `develop` branch. There are official docker images available (onetimesecret/onetimesecret:latest) as well.
