### ISSUE TITLE
Critical UX issue for inexperienced users

### ISSUE THREAD

**Issue by shakiba** [onetimesecret/onetimesecret#276]
Hi,

I recently used your website to share a password with someone who was not tech savvy. They somehow missed to capture the password in the first attempt, so I decided to make a phone call to read the password for them. However I realized they were completely confused with expired secret page and it took very long time until I figure out the issue and correct it.

The problem was that currently when a secret is expired, the feedback message is muted, and the "Share a secret of your own" is completely dominant.

So in this case because the secret was expired, they clicked on "Share a secret of your own". Then when I called to read the password over the phone, they were still on the new secret page, and they were completely confused about what to do with the password.

It took several minutes until I realized what the issue is, and it took several more minutes to guide them to close your website completely and do not open the link any more, and instead go back to a previous email (which was difficult for them to find), and open the link that was in the previous email to use the password that I was reading over the phone.

Even after they used the password successfully, they again opened the link to your website and clicked on the button to create a new secret, and were still confused what to do with your website link next. They were still wondering if they should still somehow use the password with your website to store it for another time or something like that. And they were wondering if there is nothing to do with your website why I sent it in the first place.

I think it would be helpful if the page for viewing secret always has a terminal state design (for valid, expired and incorrect links), so a receiver is not guided into the flow for making a new secret or something else by mistake.

<img width="798" alt="Screenshot 2023-12-30 at 8 01 02 PM" src="https://github.com/onetimesecret/onetimesecret/assets/1061095/7d7250de-a024-46f7-8c57-64f28ce29ce5">

**Comment by prashant-chai** [comment]
Haha this completely makes sense

**Comment by delano** [comment]
@shakiba Wow, yeah. Thanks for taking the time to write all that out. I understand exactly what you mean. I'm sorry it's taken me so long to respond and for how frustrating this would be for everyone involved. 

I'm going to hotfix it now.

**Comment by delano** [comment]
This should do the trick until the next redesign.

![No such secret - One Time · 11 49 · 04-06](https://github.com/onetimesecret/onetimesecret/assets/1206/ab434dab-a707-433b-a988-81f716e99e90)

**Comment by shakiba** [comment]
Hi Delano, 
The fix looks great; thanks for your work!
