### ISSUE TITLE
cant build the docker image

### ISSUE THREAD

**Issue by terminaldweller** [onetimesecret/onetimesecret#278]
running `docker compose build app` on `v0.11.0` results in:
```
 => ERROR [app builder 3/5] RUN gem update --system                                                                                                                                      16.8s
 ------
  > [app builder 3/5] RUN gem update --system:
  > 16.70 ERROR:  Error installing rubygems-update:
  > 16.70   There are no versions of rubygems-update (= 3.5.5) compatible with your Ruby & RubyGems
  > 16.70   rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.6.10.210.
  > 16.71 ERROR:  While executing gem ... (NoMethodError)
  > 16.71     undefined method `version' for nil:NilClass
  > 16.72 Updating rubygems-update
  > ------
  > failed to solve: process "/bin/sh -c gem update --system" did not complete successfully: exit code: 1""'))]]
```

**Comment by milad-amirianfar-azihub** [comment]
me too

**Comment by chanc201** [comment]
It looks like the Ruby version is too low:
"rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.6.10.210."
Try changing FROM ruby:2.6-slim AS builder to FROM ruby:3.2.0-slim AS builder in Dockerfile

**Comment by milad-amirianfar-azihub** [comment]
I already did that and works for me: FROM ruby:3.3.0-slim AS builder

**Comment by rcarrascoz** [comment]
Hi, if i put 3.3.0.slim, when I start up it says this:
docker logs -f onetime-app
[Fri Mar 15 13:14:51 UTC 2024] INFO: Running entrypoint.sh...
Bundler 2.5.6 is running, but your lockfile was generated with 2.4.12. Installing Bundler 2.4.12 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.4.12
Installing bundler 2.4.12
Fetching gem metadata from https://rubygems.org/...........
Using addressable 2.2.6
Fetching highline 2.1.0
Using attic 0.5.3
Using bcrypt 3.1.17
Using bundler 2.4.12
Using byebug 11.1.0
Using ruby-dap 0.1.3
Using daemons 1.4.1
Using drydock 0.6.9
Using encryptor 3.0.0
Using eventmachine 1.2.7
Using multi_json 1.15.0
Using redis 2.2.2
Using storable 0.8.9
Using uri-redis 0.4.2
Using multi_xml 0.6.0
Using mime-types 1.25.1
Using polyglot 0.3.5
Using mustache 0.99.3
Using rack 2.1.4.1
Using yajl-ruby 1.4.3
Using ruby_http_client 3.5.5
Using gibbler 0.8.9
Using byebug-dap 0.1.4
Using sysinfo 0.8.1
Using httparty 0.10.0
Using treetop 1.4.15
Using otto 0.4.1
Using thin 1.8.1
Using redis-dump 0.3.2
Using sendgrid-ruby 6.6.2
Using familia 0.7.1
Using mail 2.5.5
Installing highline 2.1.0
Using annoy 0.5.6
Bundle complete! 20 Gemfile dependencies, 34 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
bundler: failed to load command: thin (/usr/local/bundle/bin/thin)
bundler: failed to load command: bundle (/usr/local/bundle/bin/bundle)
/usr/local/bundle/gems/storable-0.8.9/lib/proc_source.rb:41:in `<top (required)>': uninitialized constant RubyToken (NameError)

class RubyToken::Token
      ^^^^^^^^^
Did you mean?  RubyLex
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/storable-0.8.9/lib/storable.rb:35:in `<class:Storable>'
	from /usr/local/bundle/gems/storable-0.8.9/lib/storable.rb:33:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /app/lib/onetime.rb:15:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /app/lib/onetime/app/web.rb:2:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from config.ru:19:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `instance_eval'
	from /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /usr/local/bundle/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/local/bundle/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
	from /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
	from /usr/local/bundle/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
	from /usr/local/bundle/bin/thin:25:in `load'
	from /usr/local/bundle/bin/thin:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'

Thanks!
Rafa.

**Comment by delano** [comment]
See also #289.

We've switched the develop branch over to focus on Ruby 3 work. The docker config will be sorted out as part of that.

**Comment by delano** [comment]
Initial support for Ruby 3 in line in the develop branch now. There's a basic workflow that runs tests against a matrix of ruby versions:
https://github.com/onetimesecret/onetimesecret/actions/runs/8577324066

I pushed a few updates to the Dockerfile. I'll get to the docker compose config soon as well (which I prefer to use myself over dealing with docker directly).

**Comment by delano** [comment]
Thanks @terminaldweller for raising this issue (and for the PR). Thanks @rcarrascoz @chanc201 @milad-amirianfar-azihub as well. 

The docker experience has had an overhaul now, supports Ruby 3+, and is available now on `develop`.
