### ISSUE TITLE
What does “You have been rate limited” exactly mean?

### ISSUE THREAD

**Issue by elmimmo** [onetimesecret/onetimesecret#28]
Upon trying with a wrong password to see what happened, I eventually got the error:

> Oops! Apologies dear citizen! You have been rate limited.

What does that exactly mean? Has the secret been burned?

**Comment by rugk** [comment]
I would say you made too many requests...
That's what rate limiting is.

**Comment by delano** [comment]
You can see the list of default limits here:
https://github.com/onetimesecret/onetimesecret/blob/master/etc/config#L51

I'll probably increase these soon. The purpose is to prevent abuse but I know it can be annoying if you just happen to be creating a lot of secrets.
