### ISSUE TITLE
FRAUD!

### ISSUE THREAD

**Issue by evg1n** [onetimesecret/onetimesecret#281]
Hello everyone

Someone has cloned good-old onetimesecret.com and using it to harvest secrets!

Actual website screenshot (has Delano's photo)
<img width="1272" alt="Screenshot 2024-02-16 at 21 09 34" src="https://github.com/onetimesecret/onetimesecret/assets/10906736/21da9c16-4f33-4701-8a99-e3a4de3a9674">

The fraudulent website is at ometimesecret[.]com
Fake website screenshots
<img width="1272" alt="Screenshot 2024-02-16 at 21 09 19" src="https://github.com/onetimesecret/onetimesecret/assets/10906736/d525b016-aa24-4e7f-8123-9e9b979b03c8">
<img width="1272" alt="Screenshot 2024-02-16 at 21 09 23" src="https://github.com/onetimesecret/onetimesecret/assets/10906736/1ff9e688-f1fc-4fc0-81b4-fd7a8e8f1d95">

Don't use it!

CC: @delano

**Comment by deibit** [comment]
You should probably add this to the list: hxxps://ometimesecret.com

**Comment by delano** [comment]
I reported it to:
https://urlhaus.abuse.ch/browse/
https://www.phishtank.com/
https://safebrowsing.google.com/safebrowsing/report_general/

And added a warning on the site:
![Screenshot 2024-03-15 at 21 32 42](https://github.com/onetimesecret/onetimesecret/assets/1206/82bdb18c-2ee6-4601-b015-4ed7b0a7739e)

**Comment by ghost** [comment]
> It’s tough to keep up with these. They often are buying Google AdWords ton trick more people not paying attention.

So why do you say this?

>General we can't do anything with your information even if we wanted to (which we don't). If it's a password for example, we don't know the username or even the application that the credentials are for.

here: https://secret.enuit.com/about

**Comment by delano** [comment]
> <img width="415" height="460" alt="Image" src="https://github.com/user-attachments/assets/26b33124-1699-4025-9bc1-bc2ddf271943" />
>
> Like OneTimeSecret, but real, not of lies

👍

**Comment by ghost** [comment]
You has not answered the question. If you claim you do not care about user's secrets because they are useless, why do you care about instances harvesting user's secrets?
