### ISSUE TITLE
Pbs to install on Debian 12

### ISSUE THREAD

**Issue by piotr58** [onetimesecret/onetimesecret#282]
**1) pre-recquis**
On Debian 12 "libreadline-gplv2-dev" doesn't exist. I have install "libreadline-dev"

**2) bundle install --frozen**
Said "deprecated". I must do this before
  `bundle config set --local frozen 'true'`
and
  `bundle config set --local path 'vendor/bundle'`
 and just:
`bundle install`

**3) bin/ots init crash!**
I have this:
```
bin/ots init
/home/ots/onetimesecret/vendor/bundle/ruby/3.1.0/gems/storable-0.8.9/lib/proc_source.rb:41:in `<top (required)>': uninitialized constant RubyToken (NameError)

class RubyToken::Token
      ^^^^^^^^^
Did you mean?  RubyLex
	from /home/ots/onetimesecret/vendor/bundle/ruby/3.1.0/gems/storable-0.8.9/lib/storable.rb:35:in `require'
	from /home/ots/onetimesecret/vendor/bundle/ruby/3.1.0/gems/storable-0.8.9/lib/storable.rb:35:in `<class:Storable>'
	from /home/ots/onetimesecret/vendor/bundle/ruby/3.1.0/gems/storable-0.8.9/lib/storable.rb:33:in `<top (required)>'
	from /home/ots/onetimesecret/vendor/bundle/ruby/3.1.0/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `require'
	from /home/ots/onetimesecret/vendor/bundle/ruby/3.1.0/gems/sysinfo-0.8.1/lib/sysinfo.rb:2:in `<top (required)>'
	from /home/ots/onetimesecret/lib/onetime.rb:15:in `require'
	from /home/ots/onetimesecret/lib/onetime.rb:15:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from bin/ots:9:in `<main>'
```

After research on Web I found https://github.com/onetimesecret/onetimesecret/pull/279 but no real answers…

My configuration:
Debian 12
```
ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu] 
```

Thanks for any help

**Comment by FredRa** [comment]
Got the same Issue here and tried to downgrade to Ruby 2.5 or Ruby 2.6 to use the deprecated RubyToken. But now i'am have a hassle with the bundler version. However, a downgrade should not be an option. I hope this get fixed in any way.

**Comment by delano** [comment]
Yeah Ruby 3 support has been a long time coming. I have a couple branches with some progress. What slows in down is updating individual dependencies to support it as well. Here’s one which I hope to get back to sooner than later:
https://github.com/onetimesecret/onetimesecret/pull/288/files

**Comment by delano** [comment]
Quick update. We made our last release on the current codebase (0.12.0) and have switched `develop` over to work on Ruby 3 support.

**Comment by delano** [comment]
This issue should be resolved on `develop` branch now. I'll leave this open though in case not.

**Comment by delano** [comment]
Here's the link to the latest recent for Ruby 3: https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC6

I'll close this ticket but feel free to re-open if it's still giving you probs.
