### ISSUE TITLE
E-mails are not being sent

### ISSUE THREAD

**Issue by TyboDaman** [onetimesecret/onetimesecret#285]
I am trying to use OTS through the API but e-mails are not being sent whatsoever.

**Comment by delano** [comment]
We switched email providers today so 🤞 this issue should be a thing of the past. Please let me if not though.

**Comment by paulmellors40** [comment]
Tested via the powershell library and can confirm that this is resolved. Thanks

**Comment by delano** [comment]
Great to hear. Thanks for letting me know 👌
