### ISSUE TITLE
Getting an "Unknown Secret" error. This must be widespread because another company that I deal with has the same error from their end. 

### ISSUE THREAD

**Issue by JoeySecrets** [onetimesecret/onetimesecret#287]
Getting an "Unknown Secret" error. This has been happening multiple times over the past several weeks. My company is exploring other options but I would love to say that this is resolved. 

The attachment was a screen shot from one of our vendors that is having the same problem with OneTimeSecret.  I experienced this several times over the past few weeks and I know something is up because we send OneTime links all the time to the same people. 

Thank you

Joe
[OneTime Error.docx](https://github.com/onetimesecret/onetimesecret/files/14593788/OneTime.Error.docx)

**Comment by delano** [comment]
Can you share more details about whether this is via the UI or API? If it’s the UI, what time was the secret created and what was the ttl? If the API can you share the redacted details of the metadata and secret json objects? 

I didn’t look at the screenshot unfortunately given that it’s a word doc and not a regular image file. Sorry if I’m asking for details that were in there already.

**Comment by JoeySecrets** [comment]
This error is coming from the user interface.  This screenshot is from a client. I just saved it in a jpeg format. 

![ErrorOTS](https://github.com/onetimesecret/onetimesecret/assets/163342508/dfe96077-7772-4516-88f1-a3ee6530c221)
