### ISSUE TITLE
docker-compose does not work.

### ISSUE THREAD

**Issue by rcarrascoz** [onetimesecret/onetimesecret#289]
Hello, I would like to use your onetimesecrete, but our git does not work. I have done the git clone, and docker-compose build, but I think your project is little older, the libraries are deprected or with some bug. Well, in fact, when I try to start up your app container the error is the follow:

[Thu Mar 14 17:05:53 UTC 2024] INFO: Running entrypoint.sh...
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Using addressable 2.2.6
Using highline 2.1.0
Using annoy 0.5.6
Using attic 0.5.3
Using bcrypt 3.1.17
Using bundler 2.4.12
Using byebug 11.1.0
Using ruby-dap 0.1.3
Using byebug-dap 0.1.4
Using daemons 1.4.1
Using drydock 0.6.9
Using encryptor 3.0.0
Using eventmachine 1.2.7
Using gibbler 0.8.9
Using multi_json 1.15.0
Using redis 2.2.2
Using storable 0.8.9
Using uri-redis 0.4.2
Using familia 0.7.1
Using multi_xml 0.6.0
Using httparty 0.10.0
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.5
Using mustache 0.99.3
Using rack 2.1.4.1
Using otto 0.4.1
Using yajl-ruby 1.4.3
Using redis-dump 0.3.2
Using ruby_http_client 3.5.5
Using sendgrid-ruby 6.6.2
Using sysinfo 0.8.1
Using thin 1.8.1
Bundle complete! 20 Gemfile dependencies, 34 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
/app/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
onetime[1]: no implicit conversion of nil into String
Error loading config:
onetime[1]: Error loading config:

I think some issue are on config.ru or... I don't know :)
Please, if you have some help for me, I will glad! (I am sorry for my English)

Lookinbg forward to hearing from you,
Best regards,
Rafa.

**Comment by delano** [comment]
Thanks for the report. The develop branch has switched over to supporting Ruby 3. The docker setup will be fixed as part of this work.

**Comment by delano** [comment]
The `develop` branch now supports Ruby 3+ ([v0.13.0-RC1](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC1)). If you have a chance to give it another go, I'm interested to hear how it goes. 

Still plenty more improvements to come mind you.

**Comment by adnansakel** [comment]
I am also facing same error from `develop` branch
```
» docker compose up                                                                                                                                     jadnansakel@Jahiduls-MBP
[+] Running 2/0
 ✔ Container onetime-redis  Created                                                                                                                                                                          0.0s
 ✔ Container onetime-app    Created                                                                                                                                                                          0.0s
Attaching to onetime-app, onetime-redis
onetime-redis  | 1:C 09 Apr 2024 15:56:21.966 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
onetime-redis  | 1:C 09 Apr 2024 15:56:21.966 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
onetime-redis  | 1:C 09 Apr 2024 15:56:21.966 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
onetime-redis  | 1:M 09 Apr 2024 15:56:21.968 * monotonic clock: POSIX clock_gettime
onetime-redis  | 1:M 09 Apr 2024 15:56:21.978 * Running mode=standalone, port=6379.
onetime-redis  | 1:M 09 Apr 2024 15:56:21.978 # Server initialized
onetime-redis  | 1:M 09 Apr 2024 15:56:21.982 * Loading RDB produced by version 7.0.15
onetime-redis  | 1:M 09 Apr 2024 15:56:21.982 * RDB age 88646 seconds
onetime-redis  | 1:M 09 Apr 2024 15:56:21.982 * RDB memory usage when created 0.83 Mb
onetime-redis  | 1:M 09 Apr 2024 15:56:21.982 * Done loading RDB, keys loaded: 0, keys expired: 0.
onetime-redis  | 1:M 09 Apr 2024 15:56:21.982 * DB loaded from disk: 0.001 seconds
onetime-redis  | 1:M 09 Apr 2024 15:56:21.982 * Ready to accept connections
onetime-app    | [Tue Apr  9 15:56:22 UTC 2024] INFO: Running entrypoint.sh...
onetime-app    | Fetching gem metadata from https://rubygems.org/.
onetime-app    | Resolving dependencies...
onetime-app    | Installing bundler-graph 0.2.1
onetime-app    | Bundle complete! 24 Gemfile dependencies, 54 gems now installed.
onetime-app    | Use `bundle info [gemname]` to see where a bundled gem is installed.
onetime-app    | onetime[1]: no implicit conversion of nil into String
onetime-app    | Error loading config:
onetime-app    | onetime[1]: Error loading config:
onetime-app exited with code 1
```

**Comment by delano** [comment]
Hey @adnansakel, I just overhauled the Dockerfile in `develop` with much clearer instructions. That config issue specifically is resolved now. Just make sure that you copy the example configuration files into place before running the docker commands.

```shell
$ cp --preserve --no-clobber ./etc/config.example ./etc/config

        - and -

$ cp --preserve --no-clobber .env.example .env
```

**Comment by delano** [comment]
For posterity, see also discussion on #278.
