### ISSUE TITLE
Why don't use BGSAVE?

### ISSUE THREAD

**Issue by rugk** [onetimesecret/onetimesecret#31]
Quoting from http://redis.io/commands/save:

> You almost never want to call SAVE in production environments where it will block all the other clients. Instead usually BGSAVE is used. 

So why do you recommend "save" for "light traffic"?

**Comment by delano** [comment]
This may have changed for more recent versions of redis, but if there are no save lines in the config, the `.rdb` file will never be created (incl on shutdown).
