### ISSUE TITLE
Migrate to new VM

### ISSUE THREAD

**Issue by sa1xx** [onetimesecret/onetimesecret#321]
Would like to migrate my old v0.9.2 ots to a new VM with new version of ots. 
What files would I need to copy to the new server to keep created secrets?

**Comment by delano** [comment]
If you're moving the app and redis to a new VM, you need to copy two things: 
1. The etc/onetime/config file.
2. The redis.rdb file.

If the redis server is staying the same, you only need to copy the OTS config file. It's a good practice to create a backup anyway though, just in case.

### Config file

For the config file, the only setting that needs to remain the same is the `:secret`. It's used in the encryption key so without it, the system won't be able to decrypt any existing secrets (creating from the v0.9.2 instance). 

### Redis backup

You can create an up-to-date .rdb file using `redis-cli`. Here's a good article that covers the steps involved:
https://simplebackups.com/blog/the-complete-redis-backup-guide-with-examples/

(There's also a ruby tool called [`redis-dump`](https://github.com/delano/redis-dump), that dumps everything in redis to a JSON file. However it's very old and may not be compatible with newer versions of redis-server.)

 
### A few notes

1. Before starting the migration process, be sure to stop the v0.9.2 instance first. This guarantees that there's no more data being written to redis. 
2. OTS versions v0.13.0+ are meant to be running on Ruby 3.2+. 
3. Just an FYI that there are official docker images available now: https://hub.docker.com/r/onetimesecret/onetimesecret

**Comment by sa1xx** [comment]
Thanks a lot. 
Then my issue probably comes from the Ruby version. The Readme says "Ruby 3+: [v0.13.0-RC2]" so I'm using the Ruby package from Ubuntu which is 3.0. After opening a secret, which was generated on the old system, I get this error. New secrets work fine tho. 

`D(1714630987):  OpenSSL::Cipher::CipherError: bad decrypt
D(1714630987):  http://192.168.1.16:3000/secret/sz60q2m22b6ljagqx3d9blrs2qm6qmc
D(1714630987):  /var/lib/gems/3.0.0/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `final'
/var/lib/gems/3.0.0/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `crypt'
/var/lib/gems/3.0.0/gems/encryptor-1.1.3/lib/encryptor.rb:44:in `decrypt'
/var/lib/gems/3.0.0/gems/encryptor-1.1.3/lib/encryptor/string.rb:16:in `decrypt'
/home/ots/onetimesecret-latest/lib/onetime/models/secret.rb:88:in `decrypted_value'
/home/ots/onetimesecret-latest/lib/onetime/logic.rb:568:in `process'
/home/ots/onetimesecret-latest/lib/onetime/app/web.rb:122:in `block in secret_uri'
/home/ots/onetimesecret-latest/lib/onetime/app/web/base.rb:16:in `block in publically'
/home/ots/onetimesecret-latest/lib/onetime/app/helpers.rb:43:in `carefully'
/home/ots/onetimesecret-latest/lib/onetime/app/web/base.rb:10:in `publically'
/home/ots/onetimesecret-latest/lib/onetime/app/web.rb:116:in `secret_uri'
/var/lib/gems/3.0.0/gems/otto-1.0.1/lib/otto.rb:281:in `call'
/var/lib/gems/3.0.0/gems/otto-1.0.1/lib/otto.rb:148:in `call'
/var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
/var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
/var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
/var/lib/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/var/lib/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
/var/lib/gems/3.0.0/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
/var/lib/gems/3.0.0/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
/usr/local/bin/thin:25:in `load'
/usr/local/bin/thin:25:in `<main>'`

**Comment by delano** [comment]
I have a pretty good idea what that is. I'm going to replicate it locally and work on a fix.

**Comment by delano** [comment]
After a bunch of testing, the issue I was thinking of, had already been addressed. I've tried many permutations but haven't been able to replicate the error (including running 0.9.2 on Ruby 2.6.8 to create a secret and using the latest on develop on Ruby 3.2.0). 

`OpenSSL::Cipher::CipherError: bad decrypt` is the expected error when the encryption key used to decrypt is different than the one used to encrypt it. I just haven't been able to reproduce a scenario during a migration. 

My suggestion would be to double check that the global secret is the same as the 0.9.2 instance. Assuming they are, my grizzled, 2000s era sysadmin suggestion would be to run both the old and the new instances side by side and update the reverse proxy config (nginx or caddy etc) to send requests matching /secret to the new instance first, if that returns a 404 to the old instance. 

Btw, you can update to the latest release candidate for Ruby 3+ for the most recent fixes: [v0.13.0-RC6](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC6). Just note that the environment variable names have been changed (details are in the release notes linked).

**Comment by sa1xx** [comment]
I've tried the new version and also the docker image, both throw the same error. 
But I noticed I never set a secret. So for my old and new system it's set to":secret: CHANGEME" 
Can this create that error?

**Comment by delano** [comment]
Hmm, no it shouldn't. Is there anything else particularly different about how 0.9.2 was running compared to the latest version?

To debug further we'd need to get into the Ruby code. Is that something you're comfortable with / have the interest in doing?

**Comment by sa1xx** [comment]
That would be great since I don't know much about Ruby but modifying parts should be no problem. 
The old 0.9.2 has some cosemetic changes but nothing else.
I've reinstalled everything over the weekend and still the same error. I'm out of ideas right now. 
But I've noticed that the docker image is a bit more talkative. Here the output, maybe that gives an indication. 

```
onetime[1]: D(1714981241):  OpenSSL::Cipher::CipherError: bad decrypt
D(1714981241):  OpenSSL::Cipher::CipherError: bad decrypt
onetime[1]: D(1714981241):  http://192.168.1.16:3000/secret/gue9z12da4z74011yqkjm1o6t7mx55s
D(1714981241):  http://192.168.1.16:3000/secret/gue9z12da4z74011yqkjm1o6t7mx55s
onetime[1]: D(1714981241):  /usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `final'
/usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `crypt'
/usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor.rb:44:in `decrypt'
/usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor/string.rb:16:in `decrypt'
/app/lib/onetime/models/secret.rb:88:in `decrypted_value'
/app/lib/onetime/logic.rb:562:in `process'
/app/lib/onetime/app/web.rb:122:in `block in secret_uri'
/app/lib/onetime/app/web/base.rb:16:in `block in publically'
/app/lib/onetime/app/helpers.rb:43:in `carefully'
/app/lib/onetime/app/web/base.rb:10:in `publically'
/app/lib/onetime/app/web.rb:116:in `secret_uri'
/usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
/usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:148:in `call'
/usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
/usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
/usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
/usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
/usr/local/bundle/bin/thin:25:in `load'
/usr/local/bundle/bin/thin:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
D(1714981241):  /usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `final'
/usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `crypt'
/usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor.rb:44:in `decrypt'
/usr/local/bundle/gems/encryptor-1.1.3/lib/encryptor/string.rb:16:in `decrypt'
/app/lib/onetime/models/secret.rb:88:in `decrypted_value'
/app/lib/onetime/logic.rb:562:in `process'
/app/lib/onetime/app/web.rb:122:in `block in secret_uri'
/app/lib/onetime/app/web/base.rb:16:in `block in publically'
/app/lib/onetime/app/helpers.rb:43:in `carefully'
/app/lib/onetime/app/web/base.rb:10:in `publically'
/app/lib/onetime/app/web.rb:116:in `secret_uri'
/usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
/usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:148:in `call'
/usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
/usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
/usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
/usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
/usr/local/bundle/bin/thin:25:in `load'
/usr/local/bundle/bin/thin:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```


Bad decrypt realy sounds like wrong secret.

**Comment by sa1xx** [comment]
Thank you for your support. I just found my error. I'm just stupid ... 
It really was a wrong secret, it just wasn't placed in etc/config but in a global /etc/onetime/config ...

**Comment by delano** [comment]
Thanks for updating the ticket! Even when you end up figuring it out, it's often the case that the process of creating the ticket is what helps you do that. It also helps other people so don't hesitate to open another if you run into any other issues.
