### ISSUE TITLE
Reverse web proxy (subdirectory) - Please use relative paths!

### ISSUE THREAD

**Issue by rugk** [onetimesecret/onetimesecret#33]
I am trying to run it behind a reverse web proxy. In my case: nginx. The special thing is that the URL is in a subdirectory.
So I adapted my config from a [Etherpad](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url), but all JS and CSS requests still go to `/css` or `/js`instead of `/mysubdir/css` or `/mysubdir/js`. 

So how can I fix this?

**Comment by rugk** [comment]
Lines like [this one](https://github.com/onetimesecret/onetimesecret/blob/master/templates/web/header.mustache#L18) are the reasons for this.
Because `/css/bootstrap.min.css` is an absolute path, so it uses the domain root (`mydomain.example/css/...`).

It would be better if it could use relative paths, e.g.  `css/bootstrap.min.css`. One can even change it in this way, but this breaks sites, which already are in a subdir (e.g. `/about`), because there the relative link would have to be `../css/bootstrap.min.css`.

So you see why this is tricky. As a workaround one can just change all paths to `MySubDir/css/bootstrap.min.css`, but the best solution would of course be that OneTimeSecret uses relative paths instead of absolute ones.

**Comment by delano** [comment]
Happy to merge a pull request for this.

**Comment by rugk** [comment]
It's quite much. There are a lot of paths.

**Comment by tcarrio** [comment]
@rugk Worth considering these suggestions for handling web applications that utilize absolute pathing: 

http://serverfault.com/questions/561892/how-to-handle-relative-urls-correctly-with-a-reverse-proxy/561897#561897

**Comment by PiNotEqual3** [comment]
I don't know ruby but I found this:

config.relative_url_root = "/onetime"
RAILS_RELATIVE_URL_ROOT='/onetime'

Source: http://stackoverflow.com/a/31908843/956397

But not sure how to use it...

**Comment by rugk** [comment]
That's a nice find, but unfortunately I could not get it to work. (with the environment variable at least, I could not found the correct place where to add the `config.relative_url_root` line)

The current solution I use is to apply some patches. I use [rpl](http://rpl.sourceforge.net/) as an easy search/replace tool for this and here the commands you need to execute:
```shell
rpl -i -R '"/' '"/customSubDir/' templates
rpl -i -R "'/" "'/customSubDir/" templates

rpl -i -R "'/css" "'/customSubDir/css" lib
```

And you might also want to replace the jQuery loaded from Google with your own version:
```shell
rpl -i -R "//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" "/customSubDir/js/vendor/jquery-1.9.0.min.js" *
```
(untested)

**Comment by skinerd** [comment]
It works better if you use a subdomain like secret.domain.com instead of a location like domain.com/secret, but there are still several buttons that link to localhost:7143. Even the email verification link is for localhost.

I tried setting the :host: and :domain: parameters to secret.domain.com but some of the buttons still have the internal port number like secret.domain.com:7143

Is there any configuration setting to define the external access URL? How is this achieved at onetimesecret.com?
