### ISSUE TITLE
re: renovatebot install

### ISSUE THREAD

**Issue by venkatamutyala** [onetimesecret/onetimesecret#332]
Just following up on https://github.com/onetimesecret/onetimesecret/issues/305

@delano  can you confirm if you installed this: https://github.com/apps/renovate ?

Without it being installed renovatebot won't have access to do anything. The currrent configurations will make PR's for you. So you should not have to worry about anything being merged/changed without your explicit consent.

**Comment by delano** [comment]
Haha, I started to install it and then promptly forgot about it. Done now 👌

**Comment by venkatamutyala** [comment]
Excellent! Here you are: https://github.com/onetimesecret/onetimesecret/issues/333
