### ISSUE TITLE
Special characters cause errors

### ISSUE THREAD

**Issue by rugk** [onetimesecret/onetimesecret#37]
Special characters such as German umlauts (ä, ö, ü) in the secret lead to this error message:

As a test content you can e.g. use `däöüre`

> **Error**
> Ups! An error occurred :[ 

Additionally I wonder whether the encryption is correctly done when such characters already lead to failures. Am I right that the secrets are de- & encrypted on the server?

**Comment by rugk** [comment]
Especially it is interesting that - if you set a password - the submission works, but when you use the URl to access the secret and enter the (correct) password, it also shows the same error.

**Comment by HerrStinson** [comment]
Same here. I have it installed and run by nginx/passenger. nginx logs are reporting this:
`App 12800 stdout:
App 12845 stdout:
App 12800 stderr: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
App 12800 stderr:
App 12800 stderr: http://onetimesecret.pharma-mall.de
App 12800 stderr:
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/mustache-0.99.3/lib/mustache/template.rb:39:in 'render'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/mustache-0.99.3/lib/mustache/template.rb:43:in 'render'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/mustache-0.99.3/lib/mustache.rb:119:in 'render'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/lib/onetime/app/web.rb:145:in 'block in private_uri'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/lib/onetime/app/web/base.rb:16:in 'block in publically'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/lib/onetime/app/helpers.rb:39:in 'carefully'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/lib/onetime/app/web/base.rb:10:in 'publically'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/lib/onetime/app/web.rb:138:in 'private_uri'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/otto-0.4.1/lib/otto.rb:281:in 'call'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/otto-0.4.1/lib/otto.rb:148:in 'call'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:134:in 'call'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in 'block in call'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in 'each'
App 12800 stderr: /usr/local/onetimesecret-0.9.2/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in 'call'
App 12800 stderr: /usr/local/src/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in 'process_request'
App 12800 stderr: /usr/local/src/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in 'accept_and_process_next_request'
App 12800 stderr: /usr/local/src/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in 'main_loop'
App 12800 stderr: /usr/local/src/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in 'block (3 levels) in start_threads'
App 12800 stderr: /usr/local/src/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/utils.rb:113:in 'block in create_thread_and_abort_on_exception'
App 12800 stderr:`

**Comment by rugk** [comment]
@HerrStinson BTW: Have a look [here](https://guides.github.com/features/mastering-markdown/) at "code". You can use \`\`\` to add a multi-line code (or in this case: log) snippet without breaking the line breaks.

**Comment by CHERTS** [comment]
When will this problem be solved?

OTS can not be viewed secret in Russian language.

**Comment by js94x** [comment]
Same problem here... 👎

**Comment by delano** [comment]
I'm looking into this today. Apologies for the delay.

**Comment by delano** [comment]
I was finally able to replicate. This should now be fix in production and will be included in the 0.10 release. 

I will close for now but reopen if you see any related issues.
