### ISSUE TITLE
Error loading config: /etc/onetime/config

### ISSUE THREAD

**Issue by CHERTS** [onetimesecret/onetimesecret#39]
Hi

I have the following server configuration:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie

I use RVM
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

$ bundle install
Using addressable 2.2.6
Using highline 1.6.19
Using attic 0.5.3
Using bcrypt-ruby 3.0.0
Using crack 0.1.8
Using daemons 1.1.9
Using drydock 0.6.9
Using encryptor 1.1.3
Using eventmachine 1.0.4
Using multi_json 1.8.0
Using redis 2.2.2
Using storable 0.8.9
Using uri-redis 0.4.2
Using mime-types 1.25
Using polyglot 0.3.3
Using mustache 0.99.3
Using rack 1.4.5
Using yajl-ruby 1.1.0
Using bundler 1.12.5
Using annoy 0.5.6
Using gibbler 0.8.9
Using httparty 0.7.7
Using sysinfo 0.7.3
Using treetop 1.4.15
Using otto 0.4.1
Using thin 1.5.0
Using redis-dump 0.3.2
Using familia 0.7.1
Using mail 2.5.4
Bundle complete! 18 Gemfile dependencies, 29 gems now installed.
Gems in the group dev were not installed.
Bundled gems are installed into ./vendor/bundle.

$ whoami
web101

$ ls -l /etc/onetime/config
-rw-r--r-- 1 web101 client2 1886 Sep  9 15:47 /etc/onetime/config

$ bundle exec thin -e dev -R config.ru -p 7143 -D start
Error loading config: /etc/onetime/config

how to correct it?

**Comment by onetimesecret** [comment]
Hi thanks for letting me know. There was an error in the config:
https://github.com/onetimesecret/onetimesecret/commit/b989cb38a87bd67ac19e77449bf421bb0088b52f

This is fixed in the master branch.

**Comment by CHERTS** [comment]
Thanks, it worked.
