### ISSUE TITLE
Error on colonel page - Oops! An unexpected error occurred :[ 

### ISSUE THREAD

**Issue by MirRad** [onetimesecret/onetimesecret#440]
On new implementation I've issues with colonel page after login. On colonel page I get error as shown in attachment.
All other functions and pages works fine.

On CLI I see following

D(1718660269):  NoMethodError: undefined method `[]' for nil:NilClass
D(1718660269):  http://localhost:3000/colonel/
D(1718660269):  /opt/ots/onetimesecret/lib/onetime/app/colonel.rb:62:in `init'
/opt/ots/onetimesecret/lib/onetime/app/web/views.rb:97:in `initialize'
/opt/ots/onetimesecret/lib/onetime/app/colonel.rb:53:in `initialize'
/opt/ots/onetimesecret/lib/onetime/app/colonel.rb:9:in `new'
/opt/ots/onetimesecret/lib/onetime/app/colonel.rb:9:in `block in index'
/opt/ots/onetimesecret/lib/onetime/app/web/base.rb:35:in `block in colonels'
/opt/ots/onetimesecret/lib/onetime/app/helpers.rb:43:in `carefully'
/opt/ots/onetimesecret/lib/onetime/app/web/base.rb:31:in `colonels'
/opt/ots/onetimesecret/lib/onetime/app/colonel.rb:8:in `index'
/usr/local/share/gems/gems/otto-1.0.1/lib/otto.rb:281:in `call'
/usr/local/share/gems/gems/otto-1.0.1/lib/otto.rb:108:in `call'
/usr/local/share/gems/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
/usr/local/share/gems/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
/usr/local/share/gems/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
/usr/local/share/gems/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/usr/local/share/gems/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
/usr/local/share/gems/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
/usr/local/share/gems/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
/usr/local/bin/thin:25:in `load'
/usr/local/bin/thin:25:in `<top (required)>'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/cli.rb:455:in `exec'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/cli.rb:29:in `start'
/usr/local/share/gems/gems/bundler-2.5.10/exe/bundle:28:in `block in <top (required)>'
/usr/local/share/gems/gems/bundler-2.5.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/share/gems/gems/bundler-2.5.10/exe/bundle:20:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

![2024-06-17_23h48_04](https://github.com/onetimesecret/onetimesecret/assets/44228004/e4256fd2-f028-49fb-9f24-ae80983eaa1b)

**Comment by delano** [comment]
Thanks for reporting this. The quick fix is to add this to the end of your YAML config file:

```yaml
:stathat:
  :enabled: false
```

I've been meaning to get around to removing stathat altogether. We used to use them to keep rudimentary counts like number of secrets. Removing the code is the proper fix for this issue. 

https://github.com/onetimesecret/onetimesecret/blob/0e86ea095e191917baceefd978f1e3417dd5e71c/lib/onetime/app/colonel.rb#L62

**Comment by MirRad** [comment]
Hello, thanks for the quick response. Workaround with adding two lines in YAML config works fine.
