### ISSUE TITLE
Login - Docker

### ISSUE THREAD

**Issue by pcdub** [onetimesecret/onetimesecret#484]
Delano, Thank you for your work creating OTS. It's awesome and works great. I've used your online version for years. I just installed the Docker version on Linux. Everything is working correctly except logins. When I go to sign in and login with the creds I signed up to this instance with, it redirects to the main page and still displays 'Sign In' instead of Logout, and does not have the Account link. Please advise. Thank you

**Comment by delano** [comment]
Hey @pcdub, you're welcome. Thanks for the kind words. 

It sounds like you just need to verify the account. This should be documented better. Or there should be a setting to allow new accounts to authenticate without verifying.

### Manually verifying an account

You can do this manually running redis-cli inside the docker container:

```
$ docker exec -it onetimesecret bash

root@6390ab3cf4d0:/app# redis-cli -u $REDIS_URL

172.17.0.2:6379> select 6
OK

172.17.0.2:6379[6]> keys *
1) "customer:user@example.com:object"
2) "onetime:customer"

172.17.0.2:6379[6]> hgetall customer:user@example.com:object
 1) "custid"
 2) "user@example.com"
 3) "role"
 4) "customer"
 5) "key"
 6) "user@example.com"
 7) "updated"
 8) "1721410941"
 9) "created"
10) "1721410941"
11) "passphrase_encryption"
12) "1"
13) "passphrase"
14) "$2a$12$Xs01V7AKF1rQwFANBh1XmumxIBRLaM1nWJDdwoBttdcq29PaxnbP2"
15) "planid"
16) "individual_v1"
17) "verified"       <---   
18) "false"          <---

172.17.0.2:6379[6]> hset customer:user@example.com:object verified true
(integer) 0

172.17.0.2:6379[6]> hgetall customer:user@example.com:object
 1) "custid"
 2) "user@example.com"
 3) "role"
 4) "customer"
 5) "key"
 6) "user@example.com"
 7) "updated"
 8) "1721411133"
 9) "created"
10) "1721410941"
11) "passphrase_encryption"
12) "1"
13) "passphrase"
14) "$2a$12$Xs01V7AKF1rQwFANBh1XmumxIBRLaM1nWJDdwoBttdcq29PaxnbP2"
15) "planid"
16) "individual_v1"
17) "verified"       <--- 
18) "true"           <---
```

**Comment by delano** [comment]
This auto-closed, sorry about that. Re-opening now and let me if you need anything else.
