### ISSUE TITLE
Disabling authentication & signups does not, in fact, disable authentication / sign-up

### ISSUE THREAD

**Issue by rfranks-securenet** [onetimesecret/onetimesecret#513]
I've disabled authentication in my config file, by including:

```
:authentication:
    :enabled: false
    :signup: false
    :signin: false
    :autoverify: false
```

However, when I visit the site, I still see a sign-up link, as seen below.
![image](https://github.com/user-attachments/assets/f0d28090-f6a5-49fc-a57d-3157ca82d58b)

When I click on the link, I am able to enter my email address and a password, and it tries to send the mail in the background:
![image](https://github.com/user-attachments/assets/17c6613c-5209-4e33-9a59-3e442fac9953)

I'd expect those config settings to disable authentication altogether, however all it seems to do is remove the top right buttons for sign-up and sign-in.

**Comment by delano** [comment]
This feature was added in #451 (from an older request #170). It disables session authentication as well but the signup routes and logic should be disabled `:signup: false`. I'll be pushing a fix for #512 today so I'll see if I can get this in too for v0.16.1.

**Comment by delano** [comment]
These changes are in the [v0.16.1-RC1](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.16.1-RC1) release and `develop`. Now, when authentication is disabled, all auth-related web and api endpoints return a 404 like they don't exist at all. 

If you get a chance to have a look, let me know it works for you.

**Comment by rfranks-securenet** [comment]
I've just tested it with v0.16.1-RC1, and it does indeed disable the sign-up. Thanks for the quick response!
