### ISSUE TITLE
Site Maintenance

### ISSUE THREAD

**Issue by EmirLogas** [onetimesecret/onetimesecret#537]
100% complete but still waiting?

![image](https://github.com/user-attachments/assets/1f9755db-0b03-4bdd-9e08-6aa66cff92e3)

**Comment by Sammeeeeeeee** [comment]
Same here

**Comment by delano** [comment]
Thanks for creating an issue. The system was in an inconsistent state after the update. It was hard to track down partly b/c it was showing this maintenance page instead of an error page. Anyway, got to the bottom of it. Sorry for any inconvenience.
