### ISSUE TITLE
Email regular expressions used are too restrictive

### ISSUE THREAD

**Issue by antonymous** [onetimesecret/onetimesecret#544]
Trying to understand why a newly created secret could not be shared (email not sent), I found [two](https://github.com/onetimesecret/onetimesecret/blob/cbad7dc7ff6699a6f12e07fd9067ea8c8e299f5c/lib/onetime/logic.rb#L71) [places](https://github.com/onetimesecret/onetimesecret/blob/cbad7dc7ff6699a6f12e07fd9067ea8c8e299f5c/lib/onetime/utils.rb#L57) (there can be more) with regexes, which expect email addresses' TLD to be 4 characters at most. [Do they really have to be so restrictive?](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_domain_name#:~:text=A%20TLD%27s%20maximum%20length%20is%2063%20characters)

**Comment by delano** [comment]
No they definitely have to be. We replaced the email validation on signup (with [Truemail](https://truemail-rb.org/#/)) a couple months ago. I haven't gotten around to following up with recipient addresses yet so thanks for raising this up. 

I have a couple other changes on the go at the moment, but I'll get to this soon.
