### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by OscarBeiro** [onetimesecret/onetimesecret#568]
Sorry to report it here, but I couldn't find another way.

A user enjoying our GLPI integration has wrongfully reported that the plugin was reporting an error, but the error was a 503 (website issue).
![image](https://github.com/user-attachments/assets/f6048299-9772-45d4-a7c8-3c240b7f103f)

For reference: https://github.com/ticgal/one-timesecret/issues/50

Regards,
By the way, great tool! :)

**Comment by delano** [comment]
Thanks for the heads up about the downtime. It's back up now. We deployed a major change yesterday and haven't found the root cause yet, but we're working on it.
