### ISSUE TITLE
hashing/encryption ?

### ISSUE THREAD

**Issue by mitrasero** [onetimesecret/onetimesecret#57]
Hi 
what hashing is used and where do i configure/change the defaults ?
Thanks

**Comment by delano** [comment]
It uses [`attr-encrypted`](https://github.com/attr-encrypted/encryptor/tree/1.1.3) which defaults to `aes-256-cbc`. There's no config option to change the encryption algorithm but if you fork the codebase you can do that using:

```ruby
Encryptor.default_options.merge!(:algorithm => 'some_algo')
```
