### ISSUE TITLE
No "burn" API call?

### ISSUE THREAD

**Issue by jrogov** [onetimesecret/onetimesecret#59]
Can you make one available please?

**Comment by delano** [comment]
Oh, good call. I missed that while adding that feature. Will do soon.

**Comment by eengstrom** [comment]
Just tried it out - WFM.  Thanks.

**Comment by chelnak** [comment]
Is this API enabled on the live site? 

Just tried it and i'm getting a 404.

**Comment by delano** [comment]
@chelnak Are you trying with the secret key or the private key? It's only works with the private key so that only the person that created the secret can burn it.

**Comment by chelnak** [comment]
The docs say to use the METADATA_KEY. Is that correct?

**Comment by delano** [comment]
That's the one yeah.

**Comment by chelnak** [comment]
@delano Did some more testing this morning. The 404 happens when you try and burn a secret that has a passphrase. 

Works fine when burning a secret without one.

**Comment by delano** [comment]
@chelnak Ah interesting. Thanks for the details. I need to think on this for a bit to sort what the right approach is for this case.

**Comment by RogovYaroslav** [comment]
@delano Thank you for adding Burn API call.
But, I have an issue. Docs say that return values are the same as Get Metadata request, which isn't quite true: you include actual Metadata-request-like data in state field of response, which's.. well, i guess not really predictable.

**Comment by eengstrom** [comment]
As you are thinking about this, could you also think about or answer why the result from using the `burn` api call results in a non-flat JSON response, as in:

    {
       "state": {
         "custid": "anon",
         "metadata_key": "m212lw3mqmfy21t62jeswmi940yvfkz",
         "secret_key": "",
         "ttl": 604800,
         "metadata_ttl": 604800,
         "secret_ttl": 604800,
         "state": "burned",
         "updated": 1493922248,
         "created": 1493922227,
         "recipient": []
       },
       "secret_shortkey": "j96kga"
     }

**Comment by delano** [comment]
Ha, just an oversight on my part. Thanks for the heads up.

**Comment by Flower7C3** [comment]
It still not works. Any solution?
