### ISSUE TITLE
anything planned to support also attached files ?

### ISSUE THREAD

**Issue by mitrasero** [onetimesecret/onetimesecret#60]
Hi 
my question is really if there is anything planned to support also attached files ...
Thanks !

**Comment by delano** [comment]
No plans for files. It's a problem b/c there's no straightforward way to be a sure a file was downloaded successfully before deleting it so it could never have the same kind of reliability of text (we delete the message before sending it so by the time you read it, we don't have it any more).

**Comment by delano** [comment]
Closing for now. Feel free to open if you have any other questions or suggestions.
