### ISSUE TITLE
Minimum TTL bug? (API)

### ISSUE THREAD

**Issue by RogovYaroslav** [onetimesecret/onetimesecret#61]
I haven't seen any upper and lower bounds for ttl for secrets. The thing is, while there's no upper bound as tests showed, there's an implicit lower bound which is 7/14 days for anon/auth accounts.

The question is, is this a bug? If not, what's the reason to forbid having secrets with smaller TTL? i'd say it's pretty convinient to be able to have, let's say, an 1-hour secret.

Also, what's the purpose of secret_ttl and metadata_ttl fields in "generate" api call?

**Comment by eengstrom** [comment]
Funny - I was just about to report the inability to specify a ttl lower than the 7/14 day defaults.  Longer works, but not shorter.

**Comment by onetimesecret** [comment]
Enforcing the minimum TTL came from the initial design. The thinking was
that it could lead to abuse or spam and then never revisited the idea so
thanks for raising the question. 1 hour seems like it could be a reasonable
me minimum.

When you create a secret, two redis keys are made. The secret and the
metadata. That's what two ttls are returned.

**Comment by RogovYaroslav** [comment]
Well, discussing it further, 1 hour seems the most appropriate to me, since I can imagine quite a few situtations where lesser ttl can be desired.
BTW, it's been said that this is for abuse prevention, but afaik there's per...day(?) secret limit you discussed right [here](https://github.com/onetimesecret/onetimesecret/issues/28). So, having these limits and considering common... user speed? I'd say the smallest still-appropriate ttl would be 1 minute. Just a proposal tho.

About s/m ttls. I understand why they are sent back, but generate have them as options. The problem here is that i checked and ttl's weren't set correspondingly to sent request. Do NOT consider this as a bug tho, 'cause I didn't tested it properly. 'll open another issue if I confirm my assumption

**Comment by delano** [comment]
Thanks for the follow up and clarification. I removed the unused query params from the docs. 

The minimum TTL was a straight up bug as evidenced here:
https://github.com/onetimesecret/onetimesecret/commit/6205fafcfa0aa10cac7db0dae08b54500a8f684b#diff-36f8bb4628f358a7841a9c9be443d52dL419

The ticket auto-closed with the commit message but feel free to re-open if you find anything else for this. And thanks all for helping make onetimesecret better.

**Comment by RogovYaroslav** [comment]
Thanks.
But providing more functionality, separate metadata_ttl and secret_ttl are could still be reasonable to have in request params. Could be said that number of situtations where it could be usable is, like, almost zero. But still, if you want such a "weird" functionality -  why not :D
