### ISSUE TITLE
API call for recent metadata not working

### ISSUE THREAD

**Issue by eengstrom** [onetimesecret/onetimesecret#62]
According to the [API docs](https://onetimesecret.com/docs/api/secrets), I should be able to get the list of metadata keys for recent created secrets when I provide my authentication creds.   As in:

`curl -u 'USERNAME:APITOKEN' -d '' https://onetimesecret.com/api/v1/private/recent`

but when I try this on the live site (https://onetimesecret.com/) it only returns:

`{
  "secret_key": "recent",
  "message": "Unknown secret"
}`

A brief stroll through the code seems to indicate that it should work.  I know this is potentially an issue with the live server, but if it's supposed to work, there might be a code issue.

**Comment by onetimesecret** [comment]
Thanks for the heads up. I'll take a look.

**Comment by delano** [comment]
@eengstrom Did some testing. Any chance you're sending a POST request instead of a GET?

**Comment by eengstrom** [comment]
Doh - yes.  Adding `-X GET` to my `curl` did the trick.  Sorry to bother you.

**Comment by eengstrom** [comment]
@delano - BTW - I noted you updated the API docs, but now you explicitly say `-X POST`, which is wrong, IIUC.

**Comment by delano** [comment]
@eengstrom Doh! Sorry about that. The documentation is fixed now as well.
