### ISSUE TITLE
ttl attribute value is decreasing even if the documentation states the opposite

### ISSUE THREAD

**Issue by callard71** [onetimesecret/onetimesecret#627]
Steps to reproduce:

1. Create a secret
2. Retrieve the metadata and note that the TTL value is different than the value at creation time
3. Retrieve again the metadata and we can see that the new TTL value is lower that the previous call

Note: Regression from 0.17.x

**Comment by delano** [comment]
Thanks so much for reporting this. I'll get to it as soon as I can. We're distracted with a DDoS on the site this week.

**Comment by delano** [comment]
@callard71 The fix will be in the 0.17.2 release later today. Thanks again for catching this.
