### ISSUE TITLE
Chars popup blocks text

### ISSUE THREAD

**Issue by albertdiad** [onetimesecret/onetimesecret#628]
The chars counter popup blocks the bottom line of the "secret content goes here field" and this is preventing me from editing a portion of the last line of the secret:
![Issue](https://github.com/user-attachments/assets/db36b1c2-4bb3-41c2-9fa8-b04b4c2f2bfa)

**Comment by delano** [comment]
Yeah that's annoying. Until I can get a fix out, if you click outside the text box anywhere it will disappear temporarily.

**Comment by delano** [comment]
This is fixed in v0.17.2 and live on onetimesecret.com.

I went ahead and removed it for now. It may come back later in a different form. Obviously one that doesn't block the text area : ]

**Comment by albertdiad** [comment]
Thank you!
