### ISSUE TITLE
Issue with /incoming fixed with change to endpoints.rb

### ISSUE THREAD

**Issue by xponentia** [onetimesecret/onetimesecret#638]
Have been using an older version of onetimesecret and finally re-deploying on a clean server, not using the docker container if that matters.

Was getting errors trying to enable the :incoming endpoint in the config.yaml file with the following errors showing up:

`E(1726434191): NameError: uninitialized constant Onetime::Logic::CreateIncoming -- http://127.0.0.1:3000/incoming -- 127.0.0.1 anon 2e2594v6qef0 en text/html; charset=utf-8 /incoming
E(1726434191): /home/ec2-user/onetimesecret/lib/onetime/app/web/endpoints.rb:126:in block in create_incoming'`

Ended up figuring out with the help of ChatGPT that the /lib/onetime/app/web/endpoints.rb needed the following line changed:

line 126:
`logic = OT::Logic::CreateIncoming.new sess, cust, req.params, locale`

to
`logic = OT::Logic::Incoming::CreateIncoming.new sess, cust, req.params, locale`

This seemed to fix the issue!  Hopefully, this helps someone else

**Comment by delano** [comment]
Great catch, I'll get that fix in.

Thanks so much for sponsoring. We have a ticket #594 for much-needed attention to the incoming functionality. I'll prioritize the UI update part of that for the v0.18.0 release. The incoming page hadn't been updated yet for our new Vue3 front-end so it looks awful at the moment 😅

**Comment by delano** [comment]
Both your fix above and the updated Incoming page UI are in `develop`.

<img width="640" alt="Screenshot 2024-09-17 at 08 30 48" src="https://github.com/user-attachments/assets/8f0635c4-46ec-40be-a040-907a228fee2a">
