### ISSUE TITLE
Default secret ttl

### ISSUE THREAD

**Issue by varnoatanil** [onetimesecret/onetimesecret#646]
Hi. 
Is there a way to set up Default TTL for secrets for anonymous users? Say 30 minutes. Not to limit max TTL. Users still must have an option to set TTL to something else. But on a new secret creation the default TTL must be 30 minutes.

**Comment by delano** [comment]
The easiest way to do that right now would be to set `selectedLifetime` to 1800 on this line:

https://github.com/onetimesecret/onetimesecret/blob/6c609fe10d1a1e454172fcca6916973579e5e55b/src/components/SecretFormPrivacyOptions.vue#L22

That default will apply to authenticated users as well. It would be great to have an option to set that so I'll add one for the upcoming v0.18.0 release. 

#### Example screenshots
![Screenshot 2024-09-20 at 09 10 09](https://github.com/user-attachments/assets/822610f4-4049-44db-8e6d-46ce89676fb1)

![Screenshot 2024-09-20 at 09 11 05](https://github.com/user-attachments/assets/4f81d164-4fa0-48a7-bd75-3e27440cc5bb)

**Comment by varnoatanil** [comment]
Thanks for your reply.
But it's not working. I'm using a docker image onetimesecret/onetimesecret. Do I need to perform additional actions to apply this change in the container?

**Comment by delano** [comment]
Ah clever. Yeah it's not as straightforward to customize the UI via docker. And with the new Vue app frontend you'll need to rebuild it after the modified file is mounted. That requires the node dependencies to be installed which are removed on the final docker images unfortunately. What a pain on your end. 

I'm going to go ahead and add a setting for a default ttl. I should have that by next week in the v0.18.2 release.

**Comment by delano** [comment]
Clicked the wrong comment button 😅

**Comment by delano** [comment]
This made it in to the [v0.18.2-rc3](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.18.2-rc3) release.
See PR #747 and `etc/config.example.yaml` for the new config options. 

https://github.com/onetimesecret/onetimesecret/blob/a78cfa2665c644cd936cc270afc7fdabbab6e663/etc/config.example.yaml#L55-L62

**Comment by varnoatanil** [comment]
Works like a charm! Thanks!
