### ISSUE TITLE
RuntimeError: ERR invalid password

### ISSUE THREAD

**Issue by ovreuc** [onetimesecret/onetimesecret#67]
Hello,

Running the line:

bundle exec thin -e dev -R config.ru -p 7143 start

Results in the following error:

bundler: failed to load command: thin (/etc/onetime/vendor/bundle/ruby/bin/thin)
RuntimeError: ERR invalid password
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:47:in `call'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis.rb:273:in `block in ping'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis.rb:18:in `synchronize'
  /etc/onetime/vendor/bundle/ruby/gems/redis-2.2.2/lib/redis.rb:272:in `ping'
  /etc/onetime/lib/onetime.rb:73:in `block in load!'
  /etc/onetime/lib/onetime.rb:73:in `times'
  /etc/onetime/lib/onetime.rb:73:in `load!'
  config.ru:28:in `block in <main>'
  /etc/onetime/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /etc/onetime/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
  /etc/onetime/vendor/bundle/ruby/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
  /etc/onetime/vendor/bundle/ruby/bin/thin:23:in `load'
  /etc/onetime/vendor/bundle/ruby/bin/thin:23:in `<top (required)>'

I have verified that the password is set up in redis: (I'm using a very simple password for testing)

redis-cli -a 12345
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>

My configured environment:

CentOS Linux release 7.3.1611 (Core)

ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

Redis server v=3.2.3 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=672aed6eb816ad6c

I've reached the point of stumped with my installation.

Thank you

**Comment by ovreuc** [comment]
Found the issue.

**Comment by msf004** [comment]
Do you recall what the issue was that you found? I know you wrote this ~6 years ago, but I am having the same issue right now:

ERR invalid password (RuntimeError)
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis.rb:273:in `block in ping'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis.rb:18:in `synchronize'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/redis-2.2.2/lib/redis.rb:272:in `ping'
	from /home/ots/onetimesecret/lib/onetime.rb:74:in `block in load!'
	from /home/ots/onetimesecret/lib/onetime.rb:74:in `times'
	from /home/ots/onetimesecret/lib/onetime.rb:74:in `load!'
	from /home/ots/onetimesecret/config.ru:30:in `block in <main>'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `instance_eval'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `initialize'
	from /home/ots/onetimesecret/config.ru:1:in `new'
	from /home/ots/onetimesecret/config.ru:1:in `<main>'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/rack/adapter/loader.rb:42:in `for'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/thin/controllers/controller.rb:170:in `load_adapter'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/thin/controllers/controller.rb:74:in `start'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
	from /opt/rh/rh-ruby26/root/usr/share/gems/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
	from /opt/rh/rh-ruby26/root/usr/bin/thin:23:in `load'
	from /opt/rh/rh-ruby26/root/usr/bin/thin:23:in `<main>'
