### ISSUE TITLE
Secret link cannot be copied on mobile device

### ISSUE THREAD

**Issue by AMS777** [onetimesecret/onetimesecret#70]
One-Time Secret cannot be used on Android devices because the generated link of a secret cannot be copied to be shared.

Any interaction with the field containing the generated link is disabled. The link gets selected when it's tapped on it, but nothing more can be performed, nor copy it or anything else.

**Comment by stephenpaulger** [comment]
On iPhone it is possible to select the link but it involves selecting a portion, scrolling the page and then selecting a bit more etc.

A copy button would be useful or if the link were in a text box I think it would be easier to select all to copy the contents.

**Comment by AMS777** [comment]
The link is already in a text box, but it's disabled. I think it's marked as "readonly", and this may interfere with the popup options to copy on mobile devices.

A button to copy the link would make the process even easier.

**Comment by delano** [comment]
Thanks for the details here guys. We specifically didn't include a copy button b/c -- at least at the time -- it required running flash in the browser (that's how long ago it was originally written). I'll look into something for this.

**Comment by kd2718** [comment]
First, thanks for this great website. I use it all the time.

I really think the site need a copy button. I have been using the site with some pretty computer illiterate people. They get confused by the no symbol. 

There is a js library that lets you copy to clipboard for you. It doesn't use flash. I have used it in the past.
[https://clipboardjs.com/](https://clipboardjs.com/)

I would love to see this or something like it implemented. If needed, I might be able to see if I can add this real quick.
