### ISSUE TITLE
Unable to view secrets after update

### ISSUE THREAD

**Issue by cbornhoft** [onetimesecret/onetimesecret#706]
A couple of clients replied to me today, saying they were unable to view shared secrets. I tried it out myself, and I'm running into the same problem. When clicking "Click to Reveal", a loading div quickly flashes and it returns to the original view.

Attempted this on Firefox 130.0 and Brave 1.70.119, both with the same issue.

I've attached a video showing the issue with a test secret. Let me know if you need more details beyond that.

[ots-20241004.webm](https://github.com/user-attachments/assets/d94a6a9d-5e87-4e1c-bea0-9483cd018d6e)

**Comment by delano** [comment]
Thanks for all the details and video. Looking into it now.

**Comment by delano** [comment]
![onetime-passphrase-20241004-2](https://github.com/user-attachments/assets/a735cb97-bd25-45cf-a08c-fffe7b033492)

The fix is live, in `develop`, and v0.18.1-rc1 release.

**Comment by cbornhoft** [comment]
Thanks for your hard work @delano!
