### ISSUE TITLE
Secret with passphrase > Cannot open link

### ISSUE THREAD

**Issue by sgani** [onetimesecret/onetimesecret#707]
Looks like secrets created with a passphrase are broken.

Steps to reproduce:
1. go to https://onetimesecret.com/
2. enter secret content and passphrase
3. click `Create a secret link`
4. try to navigate to the generated link 
5. click `Click to reveal` button
6. eventually, will see:
![Onetime-Secret-10-04-2024_05_55_PM](https://github.com/user-attachments/assets/68163c99-0fb3-4774-b384-0b9f53905d70)

**Comment by delano** [comment]
Fix is now live. Thanks for the quick report. 

![onetime-passphrase-20241004-1](https://github.com/user-attachments/assets/545f1746-0d4e-469b-9e96-bf4ebb24a955)
