### ISSUE TITLE
Editing the .mustache files or translation files

### ISSUE THREAD

**Issue by tig-timsibbald** [onetimesecret/onetimesecret#71]
First of al great tool you created! I downloaded this Github repository to test it on our local server.
I have only one question about changing the texts. I did the following steps: 
1) First edited the translations files in etc/local, but when i visit the local client with my browser nothing changed.
2) Second I edited the text directly in the .mustache files, by replacing the i18n translation tags with plain text. 
Both steps do not result in any changes because the browser keeps showing the old text. 
Even after I flushed the Redis Cache, restarted the Thin Client and the server.

I seems that the .mustache files are being build by another process, can someone shed some light how i can make my changes visible in the browser?

**Comment by delano** [comment]
Did you get this figured out?

**Comment by code2prog** [comment]
I have same issue. How to rebuild templates/ clear cache?

**Comment by delano** [comment]
There is no caching other than what thin is doing internally. If you edit the mustache files you should see the changes after restarting the process. 

Is it possible you have multiple `thin` processes running?

**Comment by borort** [comment]
I got the same issue when trying to update the translated text in etc/locale/en within the application root. nothing changed. Later I found out that the locale directory is copied to /etc/onetime the same directory with config and redis.conf files when we first setup the application. Modifying /etc/onetime/locale/en and you will see the changes.
