### ISSUE TITLE
API call to retrieve secret as JSON?

### ISSUE THREAD

**Issue by abrkn** [onetimesecret/onetimesecret#73]
Looking to retrieve a secret from code

**Comment by delano** [comment]
Have you seen this yet? 

https://onetimesecret.com/docs/api

**Comment by DietmarBlue** [comment]
We want to share secret links with our domain and use yours as "Backend", invisible for users.
Can this only be achieved by hosting onetimesecret on our own server?

**Comment by delano** [comment]
@DietmarBlue No, you can use our API for that. There is some rate limiting so if you generate a lot of secrets that may be a problem but otherwise you're good to go.

**Comment by robinmalik** [comment]
I think this can be closed given it was raised in 2017 with no replies to the original post?
