### ISSUE TITLE
Unable to install and get working

### ISSUE THREAD

**Issue by burtonmsp** [onetimesecret/onetimesecret#734]
Installing on a fresh Debian 12 install, none of the instructions work for me. Has anyone actually got a full walkthrough of how to install this? The docker install doesn't bring up a web page, the manual install instructions are missing many dependencies. I think this is the most frustrating product to install ever!

**Comment by burtonmsp** [comment]
I've discovered that in the install instructions it says to cp --preserve --no-clobber ./etc/config.example.yaml ./etc/config but this should I think have .yaml on the end.
All I get now after about 2 hours of fighting this is the favicon and page title, no page content at all. There's obviously something missing or not documented.

**Comment by delano** [comment]
That's super frustrating. Sorry for the headache. 

I've just rewritten the instructions and will be merging into `develop` branch shortly:
https://github.com/onetimesecret/onetimesecret/blob/37ebba3bebacf7bbe5874611a309417228899721/README.md

**Comment by delano** [comment]
The main README in the `develop` branch has been updated now. 
https://github.com/onetimesecret/onetimesecret/blob/develop/README.md

Let me know if anything in there is still unclear. If you'd be interested in using the hosted version with a custom domain let me know (free of charge).

**Comment by burtonmsp** [comment]
That's really kind of you to offer, thank you. I'll try a fresh install (manual method) and see how it goes :)
Thanks for your work on this

**Comment by burtonmsp** [comment]
It's still erroring on install (Debian 12)

An error occurred while installing psych (5.1.2), and Bundler cannot continue.

In Gemfile:
  rdoc was resolved to 6.7.0, which depends on
    psych
root@ots:/onetimesecret# sudo gem install psych
Building native extensions. This could take a while...
ERROR:  Error installing psych:
        ERROR: Failed to build gem native extension.

package configuration for yaml-0.1 is not found
find_header: checking for yaml.h... -------------------- no

LD_LIBRARY_PATH=.:/usr/lib/x86_64-linux-gnu "x86_64-linux-gnu-gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-3.1.0 -I/usr/include/ruby-3.1.0/ruby/backward -I/usr/incl>
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

LD_LIBRARY_PATH=.:/usr/lib/x86_64-linux-gnu "x86_64-linux-gnu-gcc -I/usr/include/x86_64-linux-gnu/ruby-3.1.0 -I/usr/include/ruby-3.1.0/ruby/backward -I/usr/include/ruby-3.1>
conftest.c:3:10: fatal error: yaml.h: No such file or directory
    3 | #include <yaml.h>
      |          ^~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <yaml.h>
/* end */



I run this: **sudo apt install build-essential libyaml-dev -y**
then I have an error with bundle install not being able to install fiddle.
I run this: **sudo apt install libffi-dev -y**
then the bundle install completes.

I now have a working system, thank you! :)

**Comment by burtonmsp** [comment]
hmm, is there any reason that /colonel gives an error 500? I can't see anything being logged apart from the error 500.
Apologies!

**Comment by delano** [comment]
Awesome. Thanks for taking the time to do that. 

I've made the updates to the README now as well:
https://github.com/onetimesecret/onetimesecret/pull/761/files

**Comment by burtonmsp** [comment]
Thanks for your hard work on this project!
