### ISSUE TITLE
suggestion : send link to mail, passphrase to slack

### ISSUE THREAD

**Issue by mitraed** [onetimesecret/onetimesecret#76]
hi 
a suggestion 
if we would have the ability to enter a destination mail and send the generated link to that address, and perhaps the password to slack or other, that would be greeeeeaaaaattttt 

in great i mean it will take ots a step forward and much more easy to use,

thanks for the awesome job

**Comment by delano** [comment]
Hey that's a good idea. I'll see what I can do.
