### ISSUE TITLE
link not secure

### ISSUE THREAD

**Issue by burtonmsp** [onetimesecret/onetimesecret#764]
When composing a secret, the link preview under the secret textarea shows https://, but when the link is generated it is only http. 
This is an issue as I only have https going to the OTS instance.

**Comment by burtonmsp** [comment]
Had to manually set SSL true in the config.yaml, it looked like it should have been the default but didn't work until I removed the ENV elements.

**Comment by delano** [comment]
Thanks for your patience. Some of the settings (like this one) go back to the very beginning of the codebase and so haven't had the benefit (yet) of a refresh.
