### ISSUE TITLE
[docker][redis] Wrong db index - db index is out of range

### ISSUE THREAD

**Issue by Yoda-BZH** [onetimesecret/onetimesecret#766]
Hello,

Using the docker image with version v0.18.2 (and v0.18.1), when using a remote redis with password auth, the db index is incorrect.

test script:
```
#!/bin/bash
set -u

COLONEL="test@example.com"
HOST="localhost:3000"
ONETIME_DEBUG="1"
PORT="3000"
RACK_ENV="production"
_REDIS_USER=""
_REDIS_PASSWORD="xxxxxxxxxx"
_REDIS_HOST="xxxxxxxxxxxx.services.mycloudprovider.example.com"
_REDIS_PORT="40129"
_REDIS_INDEX="0"
REDIS_URL="redis://$_REDIS_USER:$_REDIS_PASSWORD@$_REDIS_HOST:$_REDIS_PORT/$_REDIS_INDEX"
SSL="false"

docker run --rm -p 3000:3000 --name onetimesecret \
        -e REDIS_URL=$REDIS_URL \
        -e COLONEL=$COLONEL \
        -e HOST=$HOST \
        -e SSL=$SSL \
        -e RACK_ENV=$RACK_ENV \
        ots
```

the error is:
```
E(1728979282): Unexpected error `ERR DB index is out of range (redis://xxxxxxxxxxxx.services.mycloudprovider.example.com:40129/1)` (Redis::CommandError)
                                                                                                                               ^ this is not my value
```

The index is changed from `0` from `1`.

```
bash -x ./run.sh 
+ set -u
+ COLONEL=test@example.com
+ HOST=localhost:3000
+ ONETIME_DEBUG=1
+ PORT=3000
+ RACK_ENV=production
+ _REDIS_USER=
+ _REDIS_PASSWORD=xxxxxxxxxx
+ _REDIS_HOST=xxxxxxxxxxxx.services.mycloudprovider.example.com
+ _REDIS_PORT=40129
+ _REDIS_INDEX=0
+ REDIS_URL=redis://:xxxxxxxxxx@xxxxxxxxxxxx.services.mycloudprovider.example.com:40129/0
+ SSL=false
+ docker run --rm -p 3000:3000 --name onetimesecret -e REDIS_URL=redis://:xxxxxxxxxx@xxxxxxxxxxxx.services.mycloudprovider.example.com:40129/0 -e COLONEL=test@example.com -e HOST=localhost:3000 -e SSL=false -e RACK_ENV=production ots
[Tue Oct 15 08:01:21 UTC 2024] INFO: Running entrypoint.sh...
Skipping bundle install. Use BUNDLE_INSTALL=true to run it.
E(1728979282): Unexpected error `ERR DB index is out of range (redis://xxxxxxxxxx@xxxxxxxxxxxx.services.mycloudprovider.example.com:40129/1)` (Redis::CommandError)
```

I haven't found where the db index is changed.

Using `REDIS_URL=redis://:xxxxxxxxxx@xxxxxxxxxxxx.services.mycloudprovider.example.com:40129`, without specifying the db index results in the same error.

When forcing a custom db index (`15` for example), the error is the same, the db index is always `1`.

Thank you !

**Comment by delano** [comment]
I ran into something similar with Upstash. The redis instances they provide have just a single database so every connection is a 1-to-1. The reason you're seeing specifically `1` in the error messages is probably that the `Session` objects are stored to DB 1. 

https://github.com/onetimesecret/onetimesecret/blob/bcd5525fb4445e8dc5f1125adc38029a9888e712/lib/onetime/models/session.rb#L4-L10

I got around it by (manually) modifying all of the models to use DB 1 (or 0, I can't remember what they use). But I was just kicking the tires and didn't need to come up with a workable solution. 

I'm in the minority I think when it comes to redis supporting multiple "databases". Antirez himself considers them a mistake to have implemented them in the first place:
https://stackoverflow.com/questions/16221563/whats-the-point-of-multiple-redis-databases/36498590#36498590

### Quick fix

it'd be a pain but you could checkout the repo and modify the `db` setting in each of the models and then rebuild the docker image. 

https://github.com/onetimesecret/onetimesecret/blob/bcd5525fb4445e8dc5f1125adc38029a9888e712/README.md?plain=1#L98-L106

### Proper fix

Moving the model `db` settings to config settings where they belong. This will take me a while to get to atm with the current backlog.

**Comment by Yoda-BZH** [comment]
I tried this change :
```diff
diff --git a/lib/onetime/models/custom_domain.rb b/lib/onetime/models/custom_domain.rb
index 0ebaf1d6..2be1d8ad 100644
--- a/lib/onetime/models/custom_domain.rb
+++ b/lib/onetime/models/custom_domain.rb
@@ -29,7 +29,7 @@ require 'public_suffix'
 class Onetime::CustomDomain < Familia::Horreum
   include Gibbler::Complex
 
-  db 6
+  db 0
   prefix :customdomain
 
   feature :safe_dump
diff --git a/lib/onetime/models/customer.rb b/lib/onetime/models/customer.rb
index fba1256e..21cf8299 100644
--- a/lib/onetime/models/customer.rb
+++ b/lib/onetime/models/customer.rb
@@ -6,7 +6,7 @@ class Onetime::Customer < Familia::Horreum
   feature :safe_dump
   feature :expiration
 
-  db 6
+  db 0
   prefix :customer
 
   @global = nil
diff --git a/lib/onetime/models/email_receipt.rb b/lib/onetime/models/email_receipt.rb
index d3d64c82..13a1d7c9 100644
--- a/lib/onetime/models/email_receipt.rb
+++ b/lib/onetime/models/email_receipt.rb
@@ -5,7 +5,7 @@ class Onetime::EmailReceipt < Familia::Horreum
   feature :safe_dump
   feature :expiration
 
-  db 8
+  db 0
   ttl 14.days
 
   prefix :secret
diff --git a/lib/onetime/models/metadata.rb b/lib/onetime/models/metadata.rb
index 4fc5dec8..0de5fd35 100644
--- a/lib/onetime/models/metadata.rb
+++ b/lib/onetime/models/metadata.rb
@@ -6,7 +6,7 @@ module Onetime
     feature :safe_dump
     feature :expiration
 
-    db 7
+    db 0
     ttl 14.days
     prefix :metadata
 
diff --git a/lib/onetime/models/secret.rb b/lib/onetime/models/secret.rb
index 1b735310..50aec54d 100644
--- a/lib/onetime/models/secret.rb
+++ b/lib/onetime/models/secret.rb
@@ -6,7 +6,7 @@ module Onetime
     feature :safe_dump
     feature :expiration
 
-    db 8
+    db 0
     ttl 7.days # default only, can be overridden at create time
     prefix :secret
 
diff --git a/lib/onetime/models/session.rb b/lib/onetime/models/session.rb
index 3e821908..7c87db21 100644
--- a/lib/onetime/models/session.rb
+++ b/lib/onetime/models/session.rb
@@ -7,7 +7,7 @@ class Onetime::Session < Familia::Horreum
   feature :safe_dump
   feature :expiration
 
-  db 1
+  db 0
   ttl 20.minutes
   prefix :session
 
diff --git a/lib/onetime/models/stripe_event.rb b/lib/onetime/models/stripe_event.rb
index 9a085a9e..24dc4212 100644
--- a/lib/onetime/models/stripe_event.rb
+++ b/lib/onetime/models/stripe_event.rb
@@ -4,7 +4,7 @@ class Onetime::StripeEvent < Familia::Horreum
   feature :safe_dump
   feature :expiration
 
-  db 10
+  db 0
   ttl 5.years
   prefix :stripeevent
 
diff --git a/lib/onetime/models/subdomain.rb b/lib/onetime/models/subdomain.rb
index 7b596400..08553d4a 100644
--- a/lib/onetime/models/subdomain.rb
+++ b/lib/onetime/models/subdomain.rb
@@ -13,7 +13,7 @@ class Onetime::Subdomain < Familia::Horreum
 
   feature :safe_dump
 
-  db 6
+  db 0
 
   prefix :customer
   identifier :custid
```

Rebuilt the docker image (without cache, just to be sure), same error.

**Comment by delano** [comment]
Hmm. If you don't mind sharing which vendor it is I'll need to try reproducing it to see what's happening (or email issues@onetimesecret.com). 

We have a second docker image now, that includes the app and redis together: `onetimesecret/onetimesecret-lite`. That's another option to try in the meantime. 
https://github.com/onetimesecret/onetimesecret/blob/57d7dcc4972e9e515d39a/docs/DOCKER-lite.md

**Comment by spyric** [comment]
Hello, few times ago I migrated data from one redis server to another, and noticed that data stored not only in redis database that I set in config file, for example i set redis://redis/0 but found data in db with index 1

Is it expected behavior?

**Comment by delano** [comment]
It is expected yeah. It's been a convenient way to manage running instances. Like being able to quickly check the number of users or secrets (db 6, db 8) or to reset rate limiters by flushing db 2. 

The codebase is over 10 years old at this point. With all the services that run Redis with just the single DB now, I want to make the default setting a single DB and have the separate ones be an additional extra config.
