### ISSUE TITLE
Do you encrypt the passphrase client-side

### ISSUE THREAD

**Issue by nicolasrouanne** [onetimesecret/onetimesecret#78]
It's actually more of a question than an issue... sorry about that. Do you encrypt the `secret` client-side (i.e. on the browser)? 

I would really like the idea of knowing the server never knows about the `secret`.  I wonder if it's doable with the feature you offer though...

**Comment by delano** [comment]
The encryption happens server-side. A little discussion on why here:
https://news.ycombinator.com/item?id=5141131

If you include a passphrase, that's included in the encryption key. That passphrase is sent to the server but it's not stored so it's not possible to decrypt that data once it's at rest.
