### ISSUE TITLE
Installation instructions not complete

### ISSUE THREAD

**Issue by IS-KM** [onetimesecret/onetimesecret#81]
Good day everybody,

I tried to install the OTS with the manual and here it comes to several errors. I've already progressed a few steps but I can not fix the following error. 

> ots@ots:~/onetimesecret-0.10$

 bundle install --frozen --deployment --without=dev
Fetching gem metadata from https://rubygems.org/..........
Using addressable 2.2.6
Using highline 1.7.8
Using annoy 0.5.6
Using attic 0.5.3
Using bcrypt-ruby 3.0.0
Using bundler 1.16.1
Using crack 0.1.8
Using daemons 1.2.4
Using drydock 0.6.9
Using encryptor 1.1.3
Using eventmachine 1.2.0.1
Using gibbler 0.8.9
Using multi_json 1.12.1
Using redis 2.2.2
Using storable 0.8.9
Using uri-redis 0.4.2
Using familia 0.7.1
Using httparty 0.7.7
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using mustache 0.99.3
Using rack 1.4.5
Using otto 0.4.1
Fetching yajl-ruby 1.1.0
Installing yajl-ruby 1.1.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ots/onetimesecret-0.10/vendor/bundle/ruby/2.4.0/gems/yajl-ruby-1.1.0/ext/yajl
/usr/share/rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20180511-3631-1km21la.rb extconf.rb
creating Makefile

current directory: /home/ots/onetimesecret-0.10/vendor/bundle/ruby/2.4.0/gems/yajl-ruby-1.1.0/ext/yajl
make "DESTDIR=" clean

current directory: /home/ots/onetimesecret-0.10/vendor/bundle/ruby/2.4.0/gems/yajl-ruby-1.1.0/ext/yajl
make "DESTDIR="
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_ext.c
yajl_ext.c: In function ‘yajl_encode_part’:
yajl_ext.c:117:21: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
     yajl_gen_status status;
                     ^~~~~~
yajl_ext.c: In function ‘yajl_found_hash_key’:
yajl_ext.c:291:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         VALUE stringEncoded = rb_str_new2(buf);
         ^~~~~
yajl_ext.c: In function ‘rb_yajl_parser_parse’:
yajl_ext.c:442:17: warning: variable ‘stat’ set but not used [-Wunused-but-set-variable]
     yajl_status stat;
                 ^~~~
yajl_ext.c: In function ‘rb_yajl_encoder_enable_json_gem_ext’:
yajl_ext.c:852:22: error: ‘rb_cFixnum’ undeclared (first use in this function); did you mean ‘rb_isalnum’?
     rb_define_method(rb_cFixnum, "to_json", rb_yajl_json_ext_fixnum_to_json, -1);
                      ^~~~~~~~~~
                      rb_isalnum
yajl_ext.c:852:22: note: each undeclared identifier is reported only once for each function it appears in
yajl_ext.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
Makefile:241: recipe for target 'yajl_ext.o' failed
make: *** [yajl_ext.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/ots/onetimesecret-0.10/vendor/bundle/ruby/2.4.0/gems/yajl-ruby-1.1.0 for inspection.
Results logged to /home/ots/onetimesecret-0.10/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/yajl-ruby-1.1.0/gem_make.out

An error occurred while installing yajl-ruby (1.1.0), and Bundler cannot continue.
Make sure that `gem install yajl-ruby -v '1.1.0'` succeeds before bundling.

In Gemfile:
  redis-dump was resolved to 0.3.2, which depends on
    yajl-ruby
ots@ots:~/onetimesecret-0.10$ In Gemfile:
`

I have a new Linux with UBuntu 18.04 LTS.

Can someone help me here?

**Comment by 564456** [comment]
Привет

**Comment by 564456** [comment]
300d351210b3f4b5f875d6fb4f6166efa928260b
