### ISSUE TITLE
Character confusion caused by font in  secret textbox

### ISSUE THREAD

**Issue by kd2718** [onetimesecret/onetimesecret#85]
The secret textboxes appear to use Ariel font. This does not distinguish characters like I and l (upper i and lower l) or O and 0 (letter o and number 0).

It would be great to get a font that distinguishes these characters. Further a monospace font might help clearly displaying all characters.

Here is an example of a font that could work:
https://fonts.google.com/specimen/Inconsolata

It is monospace, has different characters for upper i and lower L. It adds a slash through the zero.

**Comment by delano** [comment]
This issue has been resolved at long last, as of v0.17.0.

![Image](https://github.com/user-attachments/assets/91a27c79-9f96-42fb-841f-f44c86d4ec98)
