### ISSUE TITLE
Lite version image ?

### ISSUE THREAD

**Issue by henri9813** [onetimesecret/onetimesecret#882]
Hello,

You mentioned in the documentation the existence of the following image:

```
ghcr.io/onetimesecret/onetimesecret:latest-lite
```

But it does not exists ?

**Comment by delano** [comment]
Cripes, sorry for the delay. That was the working path during initial development. Here's the corrected one:

```bash
  $ docker pull ghcr.io/onetimesecret/onetimesecret-lite:latest
```

https://github.com/onetimesecret/onetimesecret/pkgs/container/onetimesecret-lite

**Comment by henri9813** [comment]
Thanks !
