### ISSUE TITLE
Font Change

### ISSUE THREAD

**Issue by JonTom12** [onetimesecret/onetimesecret#96]
This might be more of a "request" than an "issue," but would you be able to change onetimesecret.com so that it utilizes a serif font? Since this is utilized to send passwords on occasion, it would be good to be able to differentiate between a capital I and a lowercase l.

**Comment by htoomik** [comment]
I very much agree with this suggestion. This is not a hypothetical problem; I got caught out by this today.

The cursor currently changes to a "blocked" icon when it is over the secret itself, which very much makes it look the secret cannot be selected & copied, and if a user wants to save the secret in e.g. a password manager, they have to type it one character at a time. This makes it even more important to be able to differentiate between all characters.

**Comment by bjornbjo** [comment]
Been hit by this too more than once. The font needs to clearly differentiate between all common chars.
